var e;e||(e=typeof Module !== 'undefined' ? Module : {});e.va||(e.va=0,e.Ab=0);e.va++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var f=b;c.total&&(f=c.total);if(c.loaded){d.j?e.N[a].loaded=c.loaded:(d.j=!0,e.N||(e.N={}),e.N[a]={loaded:c.loaded,total:f});var g=f=c=0,h;for(h in e.N){var k=e.N[h];c+=k.total;f+=k.loaded;g++}c=Math.ceil(c*e.va/g);e.setStatus&&e.setStatus("Downloading data... ("+f+"/"+c+")")}else!e.N&&e.setStatus&&e.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(){function b(a,b,c,d){this.start=a;this.end=b;this.zb=c;this.audio=d}function c(c){e.Ab++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);e.SPLIT_MEMORY&&e.printErr("warning: you should run the file packager with --no-heap-copy when SPLIT_MEMORY is used, otherwise copying into the heap may fail due to the splitting");
var d=e.getMemory(c.length);e.HEAPU8.set(c,d);b.prototype.xb=e.HEAPU8.subarray(d,d+c.length);c=a.files;for(d=0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();e.removeRunDependency("datafile_./Web/pharaoh.data")}e.FS_createPath("/","pharaoh-gm",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;e.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.xb.subarray(this.start,this.end))},finish:function(a){e.FS_createDataFile(this.name,null,
a,!0,!0,!0);e.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,f=0;f<d.length;++f)(new b(d[f].start,d[f].end,d[f].zb,d[f].audio)).open("GET",d[f].filename);e.addRunDependency("datafile_./Web/pharaoh.data");e.gb||(e.gb={});e.gb["./Web/pharaoh.data"]={be:!1};h?(c(h),h=null):g=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,e.printErr("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var d="function"===typeof e.locateFile?e.locateFile("pharaoh.data"):(e.filePackagePrefixURL||"")+"pharaoh.data",f=a.le,g=null,h=e.getPreloadedPackage?
e.getPreloadedPackage(d,f):null;h||b(d,f,function(a){g?(g(a),g=null):h=a});e.calledRun?c():(e.preRun||(e.preRun=[]),e.preRun.push(c))})({files:[{audio:0,start:0,crunched:0,end:6148,filename:"/pharaoh-gm/.DS_Store"},{audio:0,start:6148,crunched:0,end:45525,filename:"/pharaoh-gm/00000000.gm"},{audio:0,start:45525,crunched:0,end:46293,filename:"/pharaoh-gm/00000000.tt"},{audio:0,start:46293,crunched:0,end:82747,filename:"/pharaoh-gm/00000001.gm"},{audio:0,start:82747,crunched:0,end:153143,filename:"/pharaoh-gm/00000002.gm"},
{audio:0,start:153143,crunched:0,end:155275,filename:"/pharaoh-gm/0000000A.gm"},{audio:0,start:155275,crunched:0,end:228893,filename:"/pharaoh-gm/0000000A.tt"},{audio:0,start:228893,crunched:0,end:230811,filename:"/pharaoh-gm/0000000B.gm"}],remote_package_size:230811,package_uuid:"1dab388f-17ea-46dd-815a-db5c2ebd060a"});var aa={},ba;for(ba in e)e.hasOwnProperty(ba)&&(aa[ba]=e[ba]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];
var ca=!1,l=!1,m=!1,da=!1;if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)ca=!0;else if("WORKER"===e.ENVIRONMENT)l=!0;else if("NODE"===e.ENVIRONMENT)m=!0;else if("SHELL"===e.ENVIRONMENT)da=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else ca="object"===typeof window,l="function"===typeof importScripts,m="object"===typeof process&&"function"===typeof require&&!ca&&!l,da=!ca&&!m&&!l;
if(m){var ea,fa;e.read=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);a=ea.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof ha))throw a;});process.on("unhandledRejection",
function(){process.exit(1)});e.inspect=function(){return"[Emscripten Module object]"}}else if(da)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ca||l)e.read=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},"undefined"!=typeof arguments&&(e.arguments=arguments),e.setWindowTitle=
function(a){document.title=a};e.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;e.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||e.print;e.print=e.print;e.printErr=e.printErr;for(ba in aa)aa.hasOwnProperty(ba)&&(e[ba]=aa[ba]);aa=void 0;function ia(a){assert(!ja);var b=n;n=n+a+15&-16;return b}function ka(a){var b;b||(b=16);return Math.ceil(a/b)*b}
function la(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:return"*"===a[a.length-1]?4:"i"===a[0]?(a=parseInt(a.substr(1)),assert(0===a%8),a/8):0}}function ma(a){na||(na={});na[a]||(na[a]=1,e.printErr(a))}var na,oa=0;function assert(a,b){a||q("Assertion failed: "+b)}
function u(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":x[a>>0]=b;break;case "i8":x[a>>0]=b;break;case "i16":pa[a>>1]=b;break;case "i32":y[a>>2]=b;break;case "i64":tempI64=[b>>>0,(tempDouble=b,1<=+qa(tempDouble)?0<tempDouble?(ra(+sa(tempDouble/4294967296),4294967295)|0)>>>0:~~+ta((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];y[a>>2]=tempI64[0];y[a+4>>2]=tempI64[1];break;case "float":z[a>>2]=b;break;case "double":ua[a>>3]=b;break;default:q("invalid type for setValue: "+
c)}}function va(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;var f="string"===typeof b?b:null;var g=("function"===typeof wa?wa:ia)(Math.max(d,f?1:b.length));if(c){a=g;assert(0==(g&3));for(b=g+(d&-4);a<b;a+=4)y[a>>2]=0;for(b=g+d;a<b;)x[a++>>0]=0;return g}if("i8"===f)return a.subarray||a.slice?A.set(a,g):A.set(new Uint8Array(a),g),g;c=0;for(var h,k,p;c<d;){var r=a[c];h=f||b[c];0===h?c++:("i64"==h&&(h="i32"),u(g+c,r,h),p!==h&&(k=la(h),p=h),c+=k)}return g}
function B(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=A[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,A.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return ya(A,a)}var za="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ya(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&za)return za.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var k=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|k;else{var p=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|k<<6|p}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function Aa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=128|
h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}function Ba(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ca(a){var b=Ba(a)+1,c=Da(b);Aa(a,x,c,b);return c}var buffer,x,A,pa,Fa,y,D,z,ua;
function Ga(){e.HEAP8=x=new Int8Array(buffer);e.HEAP16=pa=new Int16Array(buffer);e.HEAP32=y=new Int32Array(buffer);e.HEAPU8=A=new Uint8Array(buffer);e.HEAPU16=Fa=new Uint16Array(buffer);e.HEAPU32=D=new Uint32Array(buffer);e.HEAPF32=z=new Float32Array(buffer);e.HEAPF64=ua=new Float64Array(buffer)}var Ha,n,ja,Ia,Ja,Ka,La,Na;Ha=n=Ia=Ja=Ka=La=Na=0;ja=!1;
function Oa(){q("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+Pa+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Qa=e.TOTAL_STACK||5242880,Pa=e.TOTAL_MEMORY||16777216;Pa<Qa&&e.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Pa+"! (TOTAL_STACK="+Qa+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:Pa/65536,maximum:Pa/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(Pa),e.buffer=buffer);Ga();y[0]=1668509029;pa[1]=25459;if(115!==A[2]||99!==A[3])throw"Runtime error: expected the system to be little-endian!";
function Ra(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.O;"number"===typeof c?void 0===b.ea?e.dynCall_v(c):e.dynCall_vi(c,b.ea):c(void 0===b.ea?null:b.ea)}}}var Sa=[],Ta=[],Ua=[],Va=[],Wa=[],Xa=!1;function Ya(){var a=e.preRun.shift();Sa.unshift(a)}var qa=Math.abs,ta=Math.ceil,sa=Math.floor,ra=Math.min,Za=0,$a=null,ab=null;function bb(){Za++;e.monitorRunDependencies&&e.monitorRunDependencies(Za)}
function cb(){Za--;e.monitorRunDependencies&&e.monitorRunDependencies(Za);if(0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab)){var a=ab;ab=null;a()}}e.preloadedImages={};e.preloadedAudios={};function db(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(t){q(t)}}function b(){return e.wasmBinary||!ca&&!l||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){k=a.exports;if(k.memory){a=k.memory;var b=e.buffer;a.byteLength<b.byteLength&&e.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Ga()}e.asm=k;e.usingWasm=!0;cb()}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){e.printErr("failed to asynchronously prepare wasm: "+
a);q(a)})}if("object"!==typeof WebAssembly)return e.printErr("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return e.printErr("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;bb();if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(v){return e.printErr("Module.instantiateWasm callback failed with error: "+v),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
db(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d).catch(function(a){e.printErr("wasm streaming compile failed: "+a);e.printErr("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="pharaoh.wast",f="pharaoh.wasm",g="pharaoh.temp.asm.js";"function"===typeof e.locateFile&&(db(d)||(d=e.locateFile(d)),db(f)||(f=e.locateFile(f)),db(g)||(g=e.locateFile(g)));var h={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%
b},"debugger":function(){debugger}},parent:e},k=null;e.asmPreload=e.asm;var p=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===r)var b=p(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(C){b=null;break a}b=void 0}return b};var r="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&
"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);(b=c(b))||q("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();Ha=1024;n=Ha+45904;
Ta.push({O:function(){eb()}},{O:function(){fb()}},{O:function(){gb()}},{O:function(){hb()}},{O:function(){ib()}});e.STATIC_BASE=Ha;e.STATIC_BUMP=45904;n+=16;function jb(){return!!jb.j}
var E={I:1,B:2,Jd:3,Ec:4,H:5,Oa:6,Xb:7,bd:8,ba:9,lc:10,Ka:11,Td:11,qb:12,na:13,xc:14,pd:15,oa:16,La:17,Ud:18,qa:19,Ma:20,U:21,h:22,Xc:23,pb:24,M:25,Qd:26,yc:27,ld:28,da:29,Gd:30,Qc:31,zd:32,uc:33,Dd:34,gd:42,Bc:43,mc:44,Hc:45,Ic:46,Jc:47,Pc:48,Rd:49,$c:50,Gc:51,rc:35,cd:37,cc:52,fc:53,Vd:54,Yc:55,hc:56,ic:57,sc:35,jc:59,nd:60,ad:61,Nd:62,md:63,hd:64,jd:65,Fd:66,dd:67,$b:68,Kd:69,nc:70,Ad:71,Sc:72,vc:73,ec:74,ud:76,dc:77,Ed:78,Kc:79,Lc:80,Oc:81,Nc:82,Mc:83,od:38,Na:39,Tc:36,pa:40,vd:95,yd:96,qc:104,
Zc:105,ac:97,Cd:91,sd:88,kd:92,Hd:108,pc:111,Yb:98,oc:103,Wc:101,Uc:100,Od:110,zc:112,Ac:113,Dc:115,bc:114,tc:89,Rc:90,Bd:93,Id:94,Zb:99,Vc:102,Fc:106,qd:107,Pd:109,Sd:87,wc:122,Ld:116,td:95,ed:123,Cc:84,wd:75,kc:125,rd:131,xd:130,Md:86};function kb(a){e.___errno_location&&(y[e.___errno_location()>>2]=a);return a}
var lb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",
24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",
44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",
65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",
82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",
100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",
122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function mb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function nb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=mb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ob(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function pb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function qb(){var a=Array.prototype.slice.call(arguments,0);return nb(a.join("/"))}function F(a,b){return nb(a+"/"+b)}
function rb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=mb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var sb=[];function tb(a,b){sb[a]={input:[],output:[],R:b};ub(a,vb)}
var vb={open:function(a){var b=sb[a.node.rdev];if(!b)throw new G(E.qa);a.tty=b;a.seekable=!1},close:function(a){a.tty.R.flush(a.tty)},flush:function(a){a.tty.R.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.R.Ya)throw new G(E.Oa);for(var f=0,g=0;g<d;g++){try{var h=a.tty.R.Ya(a.tty)}catch(k){throw new G(E.H);}if(void 0===h&&0===f)throw new G(E.Ka);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.R.Ga)throw new G(E.Oa);
for(var f=0;f<d;f++)try{a.tty.R.Ga(a.tty,b[c+f])}catch(g){throw new G(E.H);}d&&(a.node.timestamp=Date.now());return f}},xb={Ya:function(a){if(!a.input.length){var b=null;if(m){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=wb(b,!0)}return a.input.shift()},Ga:function(a,b){null===b||10===b?(e.print(ya(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(e.print(ya(a.output,0)),a.output=[])}},yb={Ga:function(a,b){null===b||10===b?(e.printErr(ya(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(e.printErr(ya(a.output,0)),a.output=[])}},H={s:null,m:function(){return H.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(E.I);H.s||(H.s={dir:{node:{A:H.c.A,l:H.c.l,lookup:H.c.lookup,Y:H.c.Y,rename:H.c.rename,unlink:H.c.unlink,rmdir:H.c.rmdir,readdir:H.c.readdir,symlink:H.c.symlink},stream:{D:H.f.D}},file:{node:{A:H.c.A,l:H.c.l},stream:{D:H.f.D,read:H.f.read,write:H.f.write,Pa:H.f.Pa,bb:H.f.bb,ia:H.f.ia}},link:{node:{A:H.c.A,
l:H.c.l,readlink:H.c.readlink},stream:{}},Ta:{node:{A:H.c.A,l:H.c.l},stream:zb}});c=Ab(a,b,c,d);I(c.mode)?(c.c=H.s.dir.node,c.f=H.s.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=H.s.file.node,c.f=H.s.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=H.s.link.node,c.f=H.s.link.stream):8192===(c.mode&61440)&&(c.c=H.s.Ta.node,c.f=H.s.Ta.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Cb:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},de:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array},Ua:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=H.Cb(a),a.g=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Mb:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{A:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;I(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.J=4096;b.blocks=Math.ceil(b.size/b.J);return b},
l:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&H.Mb(a,b.size)},lookup:function(){throw Bb[E.B];},Y:function(a,b,c,d){return H.createNode(a,b,c,d)},rename:function(a,b,c){if(I(a.mode)){try{var d=Cb(b,c)}catch(g){}if(d)for(var f in d.b)throw new G(E.Na);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=Cb(a,b),d;for(d in c.b)throw new G(E.Na);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new G(E.h);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.g=d;if(0===a.g&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.g=d;if(f+d<=a.g)return a.b.set(b.subarray(c,c+d),f),d}H.Ua(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.g=Math.max(a.g,f+d);return d},D:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new G(E.h);return b},Pa:function(a,b,c){H.Ua(a.node,b+c);a.node.g=Math.max(a.node.g,
b+c)},bb:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new G(E.qa);c=a.node.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.g)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=wa(d);if(!d)throw new G(E.qb);b.set(c,d)}else a=!1,d=c.byteOffset;return{ja:d,tb:a}},ia:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new G(E.qa);if(f&2)return 0;H.f.write(a,b,0,d,c,!1);return 0}}},J={ha:!1,Pb:function(){J.ha=!!process.platform.match(/^win/);
var a=process.binding("constants");a.fs&&(a=a.fs);J.Va={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Qa:function(a){return Buffer.j?Buffer.from(a):new Buffer(a)},m:function(a){assert(m);return J.createNode(null,"/",J.Xa(a.Fa.root),0)},createNode:function(a,b,c){if(!I(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new G(E.h);a=Ab(a,b,c);a.c=J.c;a.f=J.f;return a},Xa:function(a){try{var b=fs.lstatSync(a);J.ha&&(b.mode=b.mode|(b.mode&292)>>
2)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}return b.mode},o:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.m.Fa.root);b.reverse();return qb.apply(null,b)},Bb:function(a){a&=-2656257;var b=0,c;for(c in J.Va)a&c&&(b|=J.Va[c],a^=c);if(a)throw new G(E.h);return b},c:{A:function(a){a=J.o(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}J.ha&&!b.J&&(b.J=4096);J.ha&&!b.blocks&&(b.blocks=(b.size+b.J-1)/b.J|0);return{dev:b.dev,ino:b.ino,
mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,J:b.J,blocks:b.blocks}},l:function(a,b){var c=J.o(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new G(E[d.code]);}},lookup:function(a,b){var c=F(J.o(a),b);c=J.Xa(c);return J.createNode(a,b,c)},Y:function(a,b,c,d){a=J.createNode(a,b,c,d);b=J.o(a);try{I(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,
"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new G(E[f.code]);}return a},rename:function(a,b,c){a=J.o(a);b=F(J.o(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new G(E[d.code]);}},unlink:function(a,b){a=F(J.o(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}},rmdir:function(a,b){a=F(J.o(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}},readdir:function(a){a=J.o(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;
throw new G(E[b.code]);}},symlink:function(a,b,c){a=F(J.o(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new G(E[d.code]);}},readlink:function(a){var b=J.o(a);try{return b=fs.readlinkSync(b),b=Db.relative(Db.resolve(a.m.Fa.root),b)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}}},f:{open:function(a){var b=J.o(a.node);try{32768===(a.node.mode&61440)&&(a.$=fs.openSync(b,J.Bb(a.flags)))}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}},close:function(a){try{32768===(a.node.mode&
61440)&&a.$&&fs.closeSync(a.$)}catch(b){if(!b.code)throw b;throw new G(E[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.$,J.Qa(b.buffer),c,d,f)}catch(g){throw new G(E[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.$,J.Qa(b.buffer),c,d,f)}catch(g){throw new G(E[g.code]);}},D:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.$).size}catch(d){throw new G(E[d.code]);}if(0>b)throw new G(E.h);return b}}};
n+=16;n+=16;n+=16;var Eb=null,Fb={},Gb=[],Hb=1,Ib=null,Jb=!0,Kb={},G=null,Bb={};
function Lb(a,b){a=rb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Wa:!0,Ha:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ha)throw new G(E.pa);a=mb(a.split("/").filter(function(a){return!!a}),!1);var f=Eb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Cb(f,a[d]);c=F(c,a[d]);f.Z&&(!g||g&&b.Wa)&&(f=f.Z.root);if(!g||b.wa)for(g=0;40960===(f.mode&61440);)if(f=Mb(c),c=rb(ob(c),f),f=Lb(c,{Ha:b.Ha}).node,40<g++)throw new G(E.pa);}return{path:c,node:f}}
function Nb(a){for(var b;;){if(a===a.parent)return a=a.m.cb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ib.length}function Pb(a){var b=Ob(a.parent.id,a.name);a.P=Ib[b];Ib[b]=a}function Cb(a,b){var c;if(c=(c=Qb(a,"x"))?c:a.c.lookup?0:E.na)throw new G(c,a);for(c=Ib[Ob(a.id,b)];c;c=c.P){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function Ab(a,b,c,d){Rb||(Rb=function(a,b,c,d){a||(a=this);this.parent=a;this.m=a.m;this.Z=null;this.id=Hb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},Rb.prototype={},Object.defineProperties(Rb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ib:{get:function(){return I(this.mode)}},Hb:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Rb(a,b,c,d);Pb(a);return a}function I(a){return 16384===(a&61440)}var Sb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Qb(a,b){if(Jb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return E.na}else return E.na;return 0}
function Ub(a,b){try{return Cb(a,b),E.La}catch(c){}return Qb(a,"wx")}function Vb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Gb[a])return a;throw new G(E.pb);}function Wb(a,b){Xb||(Xb=function(){},Xb.prototype={},Object.defineProperties(Xb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Xb,d;for(d in a)c[d]=a[d];a=c;b=Vb(b);a.fd=b;return Gb[b]=a}var zb={open:function(a){a.f=Fb[a.node.rdev].f;a.f.open&&a.f.open(a)},D:function(){throw new G(E.da);}};
function ub(a,b){Fb[a]={f:b}}function Yb(a,b){var c="/"===b,d=!b;if(c&&Eb)throw new G(E.oa);if(!c&&!d){var f=Lb(b,{Wa:!1});b=f.path;f=f.node;if(f.Z)throw new G(E.oa);if(!I(f.mode))throw new G(E.Ma);}b={type:a,Fa:{},cb:b,Jb:[]};a=a.m(b);a.m=b;b.root=a;c?Eb=a:f&&(f.Z=b,f.m&&f.m.Jb.push(b))}function Zb(a,b,c){var d=Lb(a,{parent:!0}).node;a=pb(a);if(!a||"."===a||".."===a)throw new G(E.h);var f=Ub(d,a);if(f)throw new G(f);if(!d.c.Y)throw new G(E.I);return d.c.Y(d,a,b,c)}
function K(a,b){return Zb(a,(void 0!==b?b:511)&1023|16384,0)}function $b(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Zb(a,b|8192,c)}function ac(a,b){if(!rb(a))throw new G(E.B);var c=Lb(b,{parent:!0}).node;if(!c)throw new G(E.B);b=pb(b);var d=Ub(c,b);if(d)throw new G(d);if(!c.c.symlink)throw new G(E.I);return c.c.symlink(c,b,a)}
function bc(a){var b=Lb(a,{parent:!0}).node,c=pb(a),d=Cb(b,c);a:{try{var f=Cb(b,c)}catch(h){f=h.v;break a}var g=Qb(b,"wx");f=g?g:I(f.mode)?E.U:0}if(f)throw new G(f);if(!b.c.unlink)throw new G(E.I);if(d.Z)throw new G(E.oa);try{Kb.willDeletePath&&Kb.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.c.unlink(b,c);b=Ob(d.parent.id,d.name);if(Ib[b]===d)Ib[b]=d.P;else for(b=Ib[b];b;){if(b.P===d){b.P=d.P;break}b=b.P}try{if(Kb.onDeletePath)Kb.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Mb(a){a=Lb(a).node;if(!a)throw new G(E.B);if(!a.c.readlink)throw new G(E.h);return rb(Nb(a.parent),a.c.readlink(a))}function cc(a,b){var c;"string"===typeof a?c=Lb(a,{wa:!0}).node:c=a;if(!c.c.l)throw new G(E.I);c.c.l(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function dc(a,b,c,d){if(""===a)throw new G(E.B);if("string"===typeof b){var f=Sb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=nb(a);try{g=Lb(a,{wa:!(b&131072)}).node}catch(k){}}f=!1;if(b&64)if(g){if(b&128)throw new G(E.La);}else g=Zb(a,c,0),f=!0;if(!g)throw new G(E.B);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!I(g.mode))throw new G(E.Ma);if(!f&&(c=g?40960===(g.mode&61440)?E.pa:
I(g.mode)&&("r"!==Tb(b)||b&512)?E.U:Qb(g,Tb(b)):E.B))throw new G(c);if(b&512){c=g;var h;"string"===typeof c?h=Lb(c,{wa:!0}).node:h=c;if(!h.c.l)throw new G(E.I);if(I(h.mode))throw new G(E.U);if(32768!==(h.mode&61440))throw new G(E.h);if(c=Qb(h,"w"))throw new G(c);h.c.l(h,{size:0,timestamp:Date.now()})}b&=-641;d=Wb({node:g,path:Nb(g),flags:b,seekable:!0,position:0,f:g.f,Ub:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(ec||(ec={}),a in ec||(ec[a]=1,e.printErr("read file: "+a)));try{Kb.onOpenFile&&
(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Kb.onOpenFile(a,g))}catch(k){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function fc(a){a.Aa&&(a.Aa=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{Gb[a.fd]=null}}function hc(a,b,c){if(!a.seekable||!a.f.D)throw new G(E.da);a.position=a.f.D(a,b,c);a.Ub=[]}
function ic(a,b,c,d,f,g){if(0>d||0>f)throw new G(E.h);if(0===(a.flags&2097155))throw new G(E.ba);if(I(a.node.mode))throw new G(E.U);if(!a.f.write)throw new G(E.h);a.flags&1024&&hc(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new G(E.da);b=a.f.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&Kb.onWriteToFile)Kb.onWriteToFile(a.path)}catch(k){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+k.message)}return b}
function jc(){G||(G=function(a,b){this.node=b;this.Ob=function(a){this.v=a;for(var b in E)if(E[b]===a){this.code=b;break}};this.Ob(a);this.message=lb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},G.prototype=Error(),G.prototype.constructor=G,[E.B].forEach(function(a){Bb[a]=new G(a);Bb[a].stack="<generic error, no stack>"}))}var kc;function lc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function mc(a,b,c,d){a=F("string"===typeof a?a:Nb(a),b);return K(a,lc(c,d))}function nc(a,b){a="string"===typeof a?a:Nb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=F(a,c);try{K(d)}catch(f){}a=d}}return d}function oc(a,b,c,d){a=F("string"===typeof a?a:Nb(a),b);c=lc(c,d);return Zb(a,(void 0!==c?c:438)&4095|32768,0)}
function pc(a,b,c,d,f,g){a=b?F("string"===typeof a?a:Nb(a),b):a;d=lc(d,f);f=Zb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}cc(f,d|146);a=dc(f,"w");ic(a,c,0,c.length,0,g);fc(a);cc(f,d)}return f}
function L(a,b,c,d){a=F("string"===typeof a?a:Nb(a),b);b=lc(!!c,!!d);L.$a||(L.$a=64);var f=L.$a++<<8|0;ub(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,h=0;h<f;h++){try{var k=c()}catch(T){throw new G(E.H);}if(void 0===k&&0===g)throw new G(E.Ka);if(null===k||void 0===k)break;g++;b[d+h]=k}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(t){throw new G(E.H);}f&&(a.node.timestamp=
Date.now());return g}});return $b(a,b,f)}function qc(a,b,c){a=F("string"===typeof a?a:Nb(a),b);return ac(c,a)}
function rc(a){if(a.Hb||a.Ib||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.b=wb(e.read(a.url),!0),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||kb(E.H);return b}
function sc(a,b,c,d,f){function g(){this.Ca=!1;this.fa=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Za(a/this.chunkSize|0)[b]}};g.prototype.Nb=function(a){this.Za=a};g.prototype.Ra=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var h=this;h.Nb(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.fa[a]){var C=h.fa;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var k=new XMLHttpRequest;k.open("GET",c,!1);b!==g&&k.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(k.responseType="arraybuffer");
k.overrideMimeType&&k.overrideMimeType("text/plain; charset=x-user-defined");k.send(null);if(!(200<=k.status&&300>k.status||304===k.status))throw Error("Couldn't load "+c+". Status: "+k.status);d=void 0!==k.response?new Uint8Array(k.response||[]):wb(k.responseText||"",!0);C[a]=d}if("undefined"===typeof h.fa[a])throw Error("doXHR failed!");return h.fa[a]});if(a||!b)g=b=1,g=b=this.Za(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.sb=b;this.rb=
g;this.Ca=!0};if("undefined"!==typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.Ca||this.Ra();return this.sb}},chunkSize:{get:function(){this.Ca||this.Ra();return this.rb}}});var k=void 0}else k=c,h=void 0;var p=oc(a,b,d,f);h?p.b=h:k&&(p.b=null,p.url=k);Object.defineProperties(p,{g:{get:function(){return this.b.length}}});var r={};
Object.keys(p.f).forEach(function(a){var b=p.f[a];r[a]=function(){if(!rc(p))throw new G(E.H);return b.apply(null,arguments)}});r.read=function(a,b,c,d,f){if(!rc(p))throw new G(E.H);a=a.node.b;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};p.f=r;return p}
function tc(a,b,c,d,f,g,h,k,p,r){function t(c){function C(c){r&&r();k||pc(a,b,c,d,f,p);g&&g();cb()}var v=!1;e.preloadPlugins.forEach(function(a){!v&&a.canHandle(w)&&(a.handle(c,w,C,function(){h&&h();cb()}),v=!0)});v||C(c)}uc();var w=b?rb(F(a,b)):a;bb();"string"==typeof c?vc(c,function(a){t(a)},h):t(c)}var FS={},Rb,Xb,ec,wc={},M=0;function N(){M+=4;return y[M-4>>2]}function xc(){var a=Gb[N()];if(!a)throw new G(E.ba);return a}
function yc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var zc=void 0;function O(a){for(var b="";A[a];)b+=zc[A[a++]];return b}var Ac={},Bc={},Cc={};function Dc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Ec(a,b){a=Dc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Fc(a){var b=Error,c=Ec(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Gc=void 0;function P(a){throw new Gc(a);}var Hc=void 0;function Ic(a,b){var c=[];function d(a){a=b(a);if(a.length!==c.length)throw new Hc("Mismatched type converter count");for(var d=0;d<c.length;++d)Jc(c[d],a[d])}c.forEach(function(b){Cc[b]=a});var f=Array(a.length),g=[],h=0;a.forEach(function(a,b){Bc.hasOwnProperty(a)?f[b]=Bc[a]:(g.push(a),Ac.hasOwnProperty(a)||(Ac[a]=[]),Ac[a].push(function(){f[b]=Bc[a];++h;h===g.length&&d(f)}))});0===g.length&&d(f)}
function Jc(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||P('type "'+d+'" must have a positive integer typeid pointer');if(Bc.hasOwnProperty(a)){if(c.Eb)return;P("Cannot register type '"+d+"' twice")}Bc[a]=b;delete Cc[a];Ac.hasOwnProperty(a)&&(b=Ac[a],delete Ac[a],b.forEach(function(a){a()}))}var Kc=[],Q=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Lc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Kc.length?Kc.pop():Q.length;Q[b]={Lb:1,value:a};return b}}function Mc(a){return this.fromWireType(D[a>>2])}function Nc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Oc(a,b){switch(b){case 2:return function(a){return this.fromWireType(z[a>>2])};case 3:return function(a){return this.fromWireType(ua[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Pc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ec(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Qc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Rc(a,b){var c=e;if(void 0===c[a].u){var d=c[a];c[a]=function(){c[a].u.hasOwnProperty(arguments.length)||P("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].u+")!");return c[a].u[arguments.length].apply(this,arguments)};c[a].u=[];c[a].u[d.ub]=d}}
function Sc(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].u&&void 0!==e[a].u[c])&&P("Cannot register public name '"+a+"' twice"),Rc(a,a),e.hasOwnProperty(c)&&P("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].u[c]=b):(e[a]=b,void 0!==c&&(e[a].ke=c))}function Tc(a,b){for(var c=[],d=0;d<a;d++)c.push(y[(b>>2)+d]);return c}
function Uc(a,b){a=O(a);if(void 0!==e["FUNCTION_TABLE_"+a])var c=e["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=e.asm["dynCall_"+a];void 0===c&&(c=e.asm["dynCall_"+a.replace(/f/g,"d")],void 0===c&&P("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall",
"rawFunction",f+"};\n"))(c,b)}"function"!==typeof c&&P("unknown function pointer with signature "+a+": "+b);return c}var Vc=void 0;function Wc(a){a=Xc(a);var b=O(a);R(a);return b}function Yc(a,b){function c(a){f[a]||Bc[a]||(Cc[a]?Cc[a].forEach(c):(d.push(a),f[a]=!0))}var d=[],f={};b.forEach(c);throw new Vc(a+": "+d.map(Wc).join([", "]));}
function Zc(a,b,c){switch(b){case 0:return c?function(a){return x[a]}:function(a){return A[a]};case 1:return c?function(a){return pa[a>>1]}:function(a){return Fa[a>>1]};case 2:return c?function(a){return y[a>>2]}:function(a){return D[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var $c=0,ad=null,bd="",cd=0,dd=null,ed=0,fd=0,gd=0,hd=0,id=[],jd={},kd,ld,md,nd=!1,od=!1,pd=[];
function uc(){function a(){od=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!qd){qd=!0;try{rd=!0}catch(c){rd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}sd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:rd?null:console.log("warning: no BlobBuilder");
ud="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.eb||"undefined"!==typeof ud||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.eb=!0);e.preloadPlugins.push({canHandle:function(a){return!e.eb&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(rd)try{c=new Blob([a],{type:vd(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:vd(b)}))}catch(r){ma("Blob constructor present but fails: "+
r+"; falling back to blob builder")}c||(c=new sd,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=ud.createObjectURL(c),p=new Image;p.onload=function(){assert(p.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=p.width;c.height=p.height;c.getContext("2d").drawImage(p,0,0);e.preloadedImages[b]=c;ud.revokeObjectURL(d);f&&f(a)};p.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};p.src=d}});e.preloadPlugins.push({canHandle:function(a){return!e.je&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){p||(p=!0,e.preloadedAudios[b]=c,f&&f(a))}function d(){p||(p=!0,e.preloadedAudios[b]=new Audio,g&&g())}var p=!1;if(rd){try{var r=new Blob([a],{type:vd(b)})}catch(w){return d()}r=ud.createObjectURL(r);var t=new Audio;t.addEventListener("canplaythrough",function(){c(t)},!1);t.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,g=0,
h=0;h<a.length;h++)for(f=f<<8|a[h],g+=8;6<=g;){var k=f>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[k]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");t.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(t)}};t.src=r;wd(function(){c(t)})}else return d()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(a){!od&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function xd(a,b,c,d){if(b&&e.K&&a==e.canvas)return e.K;if(b){var f={antialias:!1,alpha:!1};if(d)for(var g in d)f[g]=d[g];if(f=yd(a,f))var h=zd[f].GLctx}else h=a.getContext("2d");if(!h)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.K=h,b&&Ad(f),e.oe=b,pd.forEach(function(a){a()}),uc());return h}var Bd=!1,Cd=void 0,Dd=void 0;
function Ed(a,b,c){function d(){nd=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),Cd&&f.requestPointerLock(),nd=!0,Dd&&("undefined"!=typeof SDL&&
(y[SDL.screen>>2]=D[SDL.screen>>2]|8388608),Fd())):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),Dd&&("undefined"!=typeof SDL&&(y[SDL.screen>>2]=D[SDL.screen>>2]&-8388609),Fd()));if(e.onFullScreen)e.onFullScreen(nd);if(e.onFullscreen)e.onFullscreen(nd);Gd(f)}Cd=a;Dd=b;Hd=c;"undefined"===typeof Cd&&(Cd=!0);"undefined"===typeof Dd&&(Dd=!1);"undefined"===typeof Hd&&(Hd=null);var f=e.canvas;Bd||(Bd=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",
d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({pe:c}):
g.requestFullscreen()}function Id(a,b,c){e.printErr("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");Id=function(a,b,c){return Ed(a,b,c)};return Ed(a,b,c)}var Jd=0;function Kd(a){var b=Date.now();if(0===Jd)Jd=b+1E3/60;else for(;b+2>=Jd;)Jd+=1E3/60;setTimeout(a,Math.max(Jd-b,0))}
function Ld(a){"undefined"===typeof window?Kd(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||Kd),window.requestAnimationFrame(a))}function wd(a){e.noExitRuntime=!0;setTimeout(function(){oa||a()},1E4)}
function vd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Md=0,Nd=0,Od=0,Pd=0;
function Qd(a){if(od)"mousemove"!=a.type&&"mozMovementX"in a?Od=Pd=0:(Od=a.movementX||a.mozMovementX||a.webkitMovementX||0,Pd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Md=SDL.he+Od,Nd=SDL.ie+Pd):(Md+=Od,Nd+=Pd);else{var b=e.canvas.getBoundingClientRect(),c=e.canvas.width,d=e.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===
a.type||"touchmove"===a.type||"touchcancel"===a.type)if("undefined"!=typeof SDL)var h=a.ne;else{for(var k=a.changedTouches,p=0;p<k.length;p++){h=k[p];var r=h.pageX-(f+b.left);h=h.pageY-(g+b.top);r*=c/b.width;h*=d/b.height;r={x:r,y:h};switch(a.type){case "touchstart":if(Rd)return;Rd=r;break;case "touchend":case "touchcancel":if(!Rd)return;Rd=null;break;case "touchmove":if(!Rd)return;Rd=r}}Rd&&(f=Rd.x,a=Rd.y,Od=f-Md,Pd=a-Nd,Md=f,Nd=a)}else f=a.pageX-(f+b.left),a=a.pageY-(g+b.top),f*=c/b.width,a*=d/
b.height,Od=f-Md,Pd=a-Nd,Md=f,Nd=a}}function vc(a,b,c){var d="al "+a;e.readAsync(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));d&&cb()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&bb()}var Sd=[];function Fd(){var a=e.canvas;Sd.forEach(function(b){b(a.width,a.height)})}function Td(a,b,c){Gd(e.canvas,a,b);c||Fd()}
function Gd(a,b,c){b&&c?(a.Vb=b,a.Db=c):(b=a.Vb,c=a.Db);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}Dd?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var qd,rd,sd,ud,Hd,Rd;
function Ud(a,b){fd=a;gd=b;if(dd)if(0==a)ad=function(){var a=Math.max(0,ld+b-Vd())|0;setTimeout(md,a)},bd="timeout";else if(1==a)ad=function(){Ld(md)},bd="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);l?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(a),postMessage({target:"setimmediate"})):
postMessage("setimmediate","*")}}ad=function(){setImmediate(md)};bd="immediate"}}function Vd(){q()}
function Wd(a,b,c,d,f){e.noExitRuntime=!0;assert(!dd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");dd=a;ed=d;var g="undefined"!==typeof d?function(){e.dynCall_vi(a,d)}:function(){e.dynCall_v(a)};var h=cd;md=function(){if(!oa)if(0<id.length){var a=Date.now(),b=id.shift();b.O(b.ea);if(kd){var c=kd,d=0==c%1?c-1:Math.floor(c);kd=b.Zd?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");e.setStatus&&(a=e.statusMessage||"Please wait...",b=kd,c=jd.ae,b?b<c?e.setStatus(a+" ("+(c-b)+"/"+c+")"):e.setStatus(a):e.setStatus(""));h<cd||setTimeout(md,0)}else if(!(h<cd))if(hd=hd+1|0,1==fd&&1<gd&&0!=hd%gd)ad();else{0==fd&&(ld=Vd());if(S)for(a=S.T,S.T=S.aa,S.aa=a,a=S.F,S.F=S.ka,S.ka=a,a=Xd[2097152],b=0;b<=a;++b)S.F[b]=0;"timeout"===bd&&e.K&&(e.printErr("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
bd="");a:if(!(oa||e.preMainLoop&&!1===e.preMainLoop())){try{g()}catch(w){if(w instanceof ha)break a;w&&"object"===typeof w&&w.stack&&e.printErr("exception thrown: "+[w,w.stack]);throw w;}e.postMainLoop&&e.postMainLoop()}h<cd||("object"===typeof SDL&&SDL.audio&&SDL.audio.Kb&&SDL.audio.Kb(),ad())}};f||(b&&0<b?Ud(0,1E3/b):Ud(1,1),ad());if(c)throw"SimulateInfiniteLoop";}var Yd=n;n+=16;var Zd,U={};
function $d(a){if(0===a)return 0;a=B(a);if(!U.hasOwnProperty(a))return 0;$d.j&&R($d.j);a=U[a];var b=Ba(a)+1,c=wa(b);c&&Aa(a,x,c,b);$d.j=c;return $d.j}var ae=1,be=0,ce=[],V=[],de=[],ee=[],W=[],zd=[],S=null,fe=0,ge=0,he=[1,1,2,2,4,4,4,2,3,4,8],ie={},je=[],ke=4;function X(a){be||(be=a)}function le(a){for(var b=ae++,c=a.length;c<b;c++)a[c]=null;return b}var me=null,ne=[0],Xd=null;
function oe(a){var b=Xd[2097152];a.F=[];a.ka=[];a.F.length=a.ka.length=b+1;a.T=[];a.aa=[];a.T.length=a.aa.length=b+1;a.S=[];a.S.length=b+1;for(var c=0;c<=b;++c){a.S[c]=null;a.F[c]=a.ka[c]=0;a.T[c]=[];a.aa[c]=[];var d=a.T[c],f=a.aa[c];d.length=f.length=64;for(var g=0;64>g;++g)d[g]=f[g]=null}}
function yd(a,b){function c(a){d=a.statusMessage||d}"undefined"===typeof b.majorVersion&&"undefined"===typeof b.minorVersion&&(b.majorVersion=1,b.minorVersion=0);var d="?";try{a.addEventListener("webglcontextcreationerror",c,!1);try{if(1==b.majorVersion&&0==b.minorVersion)var f=a.getContext("webgl",b)||a.getContext("experimental-webgl",b);else if(2==b.majorVersion&&0==b.minorVersion)f=a.getContext("webgl2",b);else throw"Unsupported WebGL context version "+majorVersion+"."+minorVersion+"!";}finally{a.removeEventListener("webglcontextcreationerror",
c,!1)}if(!f)throw":(";}catch(g){return e.print("Could not create canvas: "+[d,g,JSON.stringify(b)]),0}return f?pe(f,b):0}function pe(a,b){var c=le(zd),d={handle:c,attributes:b,version:b.majorVersion,GLctx:a};a.canvas&&(a.canvas.Wd=d);zd[c]=d;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&qe(d);return c}function Ad(a){if(a=zd[a])GLctx=e.K=a.GLctx,S=a}
function qe(a){a||(a=S);if(!a.Fb){a.Fb=!0;var b=a.GLctx;a.ab=b.getParameter(b.MAX_VERTEX_ATTRIBS);a.ga=[];for(var c=0;c<a.ab;c++)a.ga[c]={enabled:!1,ra:!1,size:0,type:0,fb:0,Ia:0,ja:0};oe(a);if(2>a.version){var d=b.getExtension("ANGLE_instanced_arrays");d&&(b.vertexAttribDivisor=function(a,b){d.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,c,f){d.drawArraysInstancedANGLE(a,b,c,f)},b.drawElementsInstanced=function(a,b,c,f,g){d.drawElementsInstancedANGLE(a,b,c,f,g)});var f=b.getExtension("OES_vertex_array_object");
f&&(b.createVertexArray=function(){return f.createVertexArrayOES()},b.deleteVertexArray=function(a){f.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){f.bindVertexArrayOES(a)},b.isVertexArray=function(a){return f.isVertexArrayOES(a)});var g=b.getExtension("WEBGL_draw_buffers");g&&(b.drawBuffers=function(a,b){g.drawBuffersWEBGL(a,b)})}b.$d=b.getExtension("EXT_disjoint_timer_query");var h="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear WEBGL_compressed_texture_atc WEBKIT_WEBGL_compressed_texture_pvrtc WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_frag_depth EXT_sRGB WEBGL_draw_buffers WEBGL_shared_resources EXT_shader_texture_lod EXT_color_buffer_float".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=h.indexOf(a)&&b.getExtension(a)})}}var re;
function _glDrawElements(a,b,c,d){if(!ge){var f=1*he[c-5120]*b;var g=Xd[f];var h=S.S[g];h?g=h:(h=GLctx.getParameter(GLctx.ELEMENT_ARRAY_BUFFER_BINDING),S.S[g]=GLctx.createBuffer(),GLctx.bindBuffer(GLctx.ELEMENT_ARRAY_BUFFER,S.S[g]),GLctx.bufferData(GLctx.ELEMENT_ARRAY_BUFFER,1<<g,GLctx.DYNAMIC_DRAW),GLctx.bindBuffer(GLctx.ELEMENT_ARRAY_BUFFER,h),g=S.S[g]);GLctx.bindBuffer(GLctx.ELEMENT_ARRAY_BUFFER,g);GLctx.bufferSubData(GLctx.ELEMENT_ARRAY_BUFFER,0,A.subarray(d,d+f));d=0}re=!1;for(f=0;f<S.ab;++f)if(g=
S.ga[f],g.ra&&g.enabled){re=!0;h=g.Ia;h=0<h?b*h:g.size*he[g.type-5120]*b;var k=Xd[h];var p=S.T[k],r=S.F[k];S.F[k]=S.F[k]+1&63;var t=p[r];t?k=t:(t=GLctx.getParameter(GLctx.ARRAY_BUFFER_BINDING),p[r]=GLctx.createBuffer(),GLctx.bindBuffer(GLctx.ARRAY_BUFFER,p[r]),GLctx.bufferData(GLctx.ARRAY_BUFFER,1<<k,GLctx.DYNAMIC_DRAW),GLctx.bindBuffer(GLctx.ARRAY_BUFFER,t),k=p[r]);GLctx.bindBuffer(GLctx.ARRAY_BUFFER,k);GLctx.bufferSubData(GLctx.ARRAY_BUFFER,0,A.subarray(g.ja,g.ja+h));GLctx.vertexAttribPointer(f,
g.size,g.type,g.fb,g.Ia,0)}GLctx.drawElements(a,b,c,d);re&&GLctx.bindBuffer(GLctx.ARRAY_BUFFER,ce[fe]);ge||GLctx.bindBuffer(GLctx.ELEMENT_ARRAY_BUFFER,null)}
function se(a,b,c,d,f){switch(b){case 6406:case 6409:case 6402:b=1;break;case 6410:b=2;break;case 6407:case 35904:b=3;break;case 6408:case 35906:b=4;break;default:return X(1280),null}switch(a){case 5121:var g=1*b;break;case 5123:case 36193:g=2*b;break;case 5125:case 5126:g=4*b;break;case 34042:g=4;break;case 33635:case 32819:case 32820:g=2;break;default:return X(1280),null}b=ke;c*=g;b*=Math.floor((c+b-1)/b);d=0>=d?0:(d-1)*b+c;switch(a){case 5121:return A.subarray(f,f+d);case 5126:return z.subarray(f>>
2,f+d>>2);case 5125:case 34042:return D.subarray(f>>2,f+d>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return Fa.subarray(f>>1,f+d>>1);default:return X(1280),null}}function te(a,b,c,d){this.id=a;this.y=this.x=0;this.za=!1;this.lb=this.kb=0;this.width=b;this.height=c;this.jb=b;this.ib=c;this.title=d;this.attributes=ue;this.buttons=0;this.keys=[];this.ta=[];this.Sa=this.Ba=this.ua=this.hb=this.V=this.sa=this.Ea=this.ya=this.ob=this.Ja=this.title=null}
function ve(a){return 0>=a||!Y?null:Y[a-1]}var Z=null,Y=null,we=null,ue=null,xe={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function ye(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function ze(){var a=Z,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Ae(a){Z&&Z.Sa&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||e.dynCall_vii(Z.Sa,Z.id,a))}
function Be(a,b){if(Z){var c=ye(a);if(-1!=c){var d=b&&Z.keys[c];Z.keys[c]=b;Z.ta[a]=b;Z.Ba&&(d&&(b=2),e.dynCall_viiiii(Z.Ba,Z.id,c,a,b,ze()))}}}function Ce(){De()}function Ee(){De()}function Fe(a){Be(a.keyCode,1)}function Ge(a){Be(a.keyCode,0)}function He(){if(Z)for(var a=0;a<Z.ta.length;++a)Z.ta[a]&&Be(a,0)}function Ie(a){Z&&(Qd(a),a.target==e.canvas&&Z.sa&&e.dynCall_vidd(Z.sa,Z.id,Md,Nd))}function Je(a){Z&&a.target==e.canvas&&Z.V&&e.dynCall_vii(Z.V,Z.id,1)}
function Ke(a){Z&&a.target==e.canvas&&Z.V&&e.dynCall_vii(Z.V,Z.id,0)}function Le(a,b){if(Z&&(Qd(a),a.target==e.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Z.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Z.buttons&=~(1<<c);Z.Ea&&e.dynCall_viiii(Z.Ea,Z.id,c,b,ze())}}function Me(a){Z&&Le(a,1)}function Ne(a){Z&&Le(a,0)}
function Oe(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Z&&Z.hb&&a.target==e.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;e.dynCall_vidd(Z.hb,Z.id,b,c);a.preventDefault()}}function Pe(){(e.canvas.requestFullscreen||e.canvas.mozRequestFullScreen||e.canvas.webkitRequestFullScreen||function(){}).apply(e.canvas,[])}var Qe={},Re=null,Se=null;
function De(){if(hd!==Se||!hd){Re=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;Se=hd;for(var a=0;a<Re.length;++a){var b=Re[a];if(b){Qe[a]||(console.log("glfw joystick connected:",a),Qe[a]={id:va(wb(b.id),"i8"),Yd:b.buttons.length,Xd:b.axes.length,buttons:va(Array(b.buttons.length),"i8"),axes:va(Array(4*b.axes.length),"float")});for(var c=Qe[a],d=0;d<b.buttons.length;++d)u(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)u(c.axes+
4*d,b.axes[d],"float")}else Qe[a]&&(console.log("glfw joystick disconnected",a),R(Qe[a].id),R(Qe[a].buttons),R(Qe[a].axes),delete Qe[a])}}}
function Te(a){function b(a){var b="/.glfw_dropped_files/"+a.name.replace(/\//g,"_"),k=new FileReader;k.onloadend=function(h){if(2!=k.readyState)++g,console.log("failed to read dropped file: "+a.name+": "+k.error);else{var p=new Uint8Array(h.target.result);h={};h.flags=h.flags||"w";var C=dc(b,h.flags,h.mode);if("string"===typeof p){var r=new Uint8Array(Ba(p)+1);p=Aa(p,r,0,r.length);ic(C,r,0,p,void 0,h.yb)}else if(ArrayBuffer.isView(p))ic(C,p,0,p.byteLength,void 0,h.yb);else throw Error("Unsupported data type");
fc(C);if(++g===f){e.dynCall_viii(Z.ua,Z.id,f,c);for(h=0;h<d.length;++h)R(d[h]);R(c)}}};k.readAsArrayBuffer(a);var t=va(wb(b),"i8");d.push(t);u(c+4*h,t,"i8*")}if(Z&&Z.ua&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=va(Array(4*a.dataTransfer.files.length),"i8*"),d=[],f=a.dataTransfer.files.length,g=0;nc("/",".glfw_dropped_files");for(var h=0;h<f;++h)b(a.dataTransfer.files[h]);return!1}}function Ue(a){if(Z&&Z.ua)return a.preventDefault(),!1}
var Ve={},We=1;function Xe(a,b){Xe.j||(Xe.j={});a in Xe.j||(e.dynCall_v(b),Xe.j[a]=1)}function Ye(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ze(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var $e=[31,29,31,30,31,30,31,31,30,31,30,31],af=[31,28,31,30,31,30,31,31,30,31,30,31];
function bf(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Ye(a.getFullYear())?$e:af)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function cf(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function k(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function p(a){a=bf(new Date(a.i+1900,0,1),a.ma);var b=k(new Date(a.getFullYear()+1,0,4));return 0>=h(k(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var r=y[d+40>>2];d={Sb:y[d>>2],Rb:y[d+4>>2],la:y[d+8>>2],L:y[d+12>>2],G:y[d+16>>2],i:y[d+20>>2],mb:y[d+24>>2],ma:y[d+28>>2],me:y[d+32>>2],Qb:y[d+36>>2],Tb:r?
B(r):""};c=B(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var t in r)c=c.replace(new RegExp(t,"g"),r[t]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),T="January February March April May June July August September October November December".split(" ");r={"%a":function(a){return w[a.mb].substring(0,3)},"%A":function(a){return w[a.mb]},"%b":function(a){return T[a.G].substring(0,
3)},"%B":function(a){return T[a.G]},"%C":function(a){return g((a.i+1900)/100|0,2)},"%d":function(a){return g(a.L,2)},"%e":function(a){return f(a.L,2," ")},"%g":function(a){return p(a).toString().substring(2)},"%G":function(a){return p(a)},"%H":function(a){return g(a.la,2)},"%I":function(a){a=a.la;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.L+Ze(Ye(a.i+1900)?$e:af,a.G-1),3)},"%m":function(a){return g(a.G+1,2)},"%M":function(a){return g(a.Rb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=
a.la&&12>a.la?"AM":"PM"},"%S":function(a){return g(a.Sb,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.i+1900,a.G+1,a.L,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.i+1900,0,1),c=0===b.getDay()?b:bf(b,7-b.getDay());a=new Date(a.i+1900,a.G,a.L);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Ze(Ye(a.getFullYear())?$e:af,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=k(new Date(a.i+1900,0,4)),c=k(new Date(a.i+1901,0,4)),d=bf(new Date(a.i+
1900,0,1),a.ma);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.i+1900?a.ma+32-b.getDate():a.ma+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.i+1900,a.G+1,a.L,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.i,0,1),c=1===b.getDay()?b:bf(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.i+1900,a.G,a.L);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Ze(Ye(a.getFullYear())?$e:af,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.i+1900).toString().substring(2)},
"%Y":function(a){return a.i+1900},"%z":function(a){a=a.Qb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Tb},"%%":function(){return"%"}};for(t in r)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),r[t](d)));t=wb(c,!1);if(t.length>b)return 0;x.set(t,a);return t.length-1}jc();Ib=Array(4096);Yb(H,"/");K("/tmp");K("/home");K("/home/web_user");
(function(){K("/dev");ub(259,{read:function(){return 0},write:function(a,b,f,g){return g}});$b("/dev/null",259);tb(1280,xb);tb(1536,yb);$b("/dev/tty",1280);$b("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else b=m?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};L("/dev","random",b);L("/dev","urandom",b);K("/dev/shm");K("/dev/shm/tmp")})();K("/proc");K("/proc/self");K("/proc/self/fd");
Yb({m:function(){var a=Ab("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=Gb[+c];if(!b)throw new G(E.ba);a={parent:null,m:{cb:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Ta.unshift(function(){if(!e.noFSInit&&!kc){assert(!kc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");kc=!0;jc();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?L("/dev","stdin",e.stdin):ac("/dev/tty","/dev/stdin");e.stdout?L("/dev","stdout",null,e.stdout):ac("/dev/tty","/dev/stdout");e.stderr?L("/dev","stderr",null,e.stderr):ac("/dev/tty1","/dev/stderr");var a=
dc("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=dc("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=dc("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Ua.push(function(){Jb=!1});Va.push(function(){kc=!1;var a=e._fflush;a&&a(0);for(a=0;a<Gb.length;a++){var b=Gb[a];b&&fc(b)}});e.FS_createFolder=mc;e.FS_createPath=nc;e.FS_createDataFile=pc;e.FS_createPreloadedFile=tc;e.FS_createLazyFile=sc;e.FS_createLink=qc;
e.FS_createDevice=L;e.FS_unlink=bc;Ta.unshift(function(){});Va.push(function(){});if(m){var fs=require("fs"),Db=require("path");J.Pb()}for(var df=Array(256),ef=0;256>ef;++ef)df[ef]=String.fromCharCode(ef);zc=df;Gc=e.BindingError=Fc("BindingError");Hc=e.InternalError=Fc("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<Q.length;++b)void 0!==Q[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Q.length;++a)if(void 0!==Q[a])return Q[a];return null};Vc=e.UnboundTypeError=Fc("UnboundTypeError");
(function(){if("undefined"!==typeof window){window.addEventListener("gamepadconnected",function(){++$c});window.addEventListener("gamepaddisconnected",function(){--$c});var a=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null;a&&($c=a.length)}})();e.requestFullScreen=function(a,b,c){e.printErr("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");e.requestFullScreen=e.requestFullscreen;Id(a,b,c)};
e.requestFullscreen=function(a,b,c){Ed(a,b,c)};e.requestAnimationFrame=function(a){Ld(a)};e.setCanvasSize=function(a,b,c){Td(a,b,c)};e.pauseMainLoop=function(){ad=null;cd++};e.resumeMainLoop=function(){cd++;var a=fd,b=gd,c=dd;dd=null;Wd(c,0,!1,ed,!0);Ud(a,b);ad()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return xd(a,b,c,d)};
m?Vd=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Vd=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?Vd=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?Vd=function(){return performance.now()}:Vd=Date.now;var ff,gf;
Zd?(gf=y[Yd>>2],ff=y[gf>>2]):(Zd=!0,U.USER=U.LOGNAME="web_user",U.PATH="/",U.PWD="/",U.HOME="/home/web_user",U.LANG="C.UTF-8",U._=e.thisProgram,ff=ia(1024),gf=ia(256),y[gf>>2]=ff,y[Yd>>2]=gf);var hf=[],jf=0,kf;for(kf in U)if("string"===typeof U[kf]){var lf=kf+"="+U[kf];hf.push(lf);jf+=lf.length}if(1024<jf)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");
for(var mf=0;mf<hf.length;mf++){for(var nf=lf=hf[mf],of=ff,pf=0;pf<nf.length;++pf)x[of++>>0]=nf.charCodeAt(pf);x[of>>0]=0;y[gf+4*mf>>2]=ff;ff+=lf.length+1}y[gf+4*hf.length>>2]=0;var GLctx;Xd=new Uint8Array(2097153);var qf=0,rf=1;Xd[0]=0;for(var sf=1;2097152>=sf;++sf)sf>rf&&(rf<<=1,++qf),Xd[sf]=qf;me=new Float32Array(256);for(var tf=0;256>tf;tf++)ne[tf]=me.subarray(0,tf+1);for(tf=0;32>tf;tf++)je.push(Array(tf));Na=ia(4);Ia=Ja=ka(n);Ka=Ia+Qa;La=ka(Ka);y[Na>>2]=La;ja=!0;
function wb(a,b){var c=Array(Ba(a)+1);a=Aa(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=718;e.wasmMaxTableSize=718;e.vb={};
e.wb={abort:q,enlargeMemory:function(){Oa()},getTotalMemory:function(){return Pa},abortOnCannotGrowMemory:Oa,__ZSt18uncaught_exceptionv:jb,___cxa_allocate_exception:function(a){return wa(a)},___cxa_throw:function(a){"uncaught_exception"in jb?jb.j++:jb.j=1;throw a+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},___lock:function(){},___map_file:function(){kb(E.I);return-1},___setErrNo:kb,___syscall140:function(a,
b){M=b;try{var c=xc();N();var d=N(),f=N(),g=N();hc(c,d,g);y[f>>2]=c.position;c.Aa&&0===d&&0===g&&(c.Aa=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof G||q(h),-h.v}},___syscall145:function(a,b){M=b;try{var c=xc(),d=N();a:{var f=N();for(b=a=0;b<f;b++){var g=y[d+(8*b+4)>>2],h=c,k=y[d+8*b>>2],p=g,r=void 0,t=x;if(0>p||0>r)throw new G(E.h);if(1===(h.flags&2097155))throw new G(E.ba);if(I(h.node.mode))throw new G(E.U);if(!h.f.read)throw new G(E.h);var w="undefined"!==typeof r;if(!w)r=
h.position;else if(!h.seekable)throw new G(E.da);var T=h.f.read(h,t,k,p,r);w||(h.position+=T);var C=T;if(0>C){var v=-1;break a}a+=C;if(C<g)break}v=a}return v}catch(Ea){return"undefined"!==typeof FS&&Ea instanceof G||q(Ea),-Ea.v}},___syscall146:function(a,b){M=b;try{var c=xc(),d=N();a:{var f=N();for(b=a=0;b<f;b++){var g=ic(c,x,y[d+8*b>>2],y[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(k){return"undefined"!==typeof FS&&k instanceof G||q(k),-k.v}},___syscall221:function(a,b){M=
b;try{var c=xc();switch(N()){case 0:var d=N();return 0>d?-E.h:dc(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=N(),c.flags|=d,0;case 12:case 12:return d=N(),pa[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-E.h;case 9:return kb(E.h),-1;default:return-E.h}}catch(f){return"undefined"!==typeof FS&&f instanceof G||q(f),-f.v}},___syscall5:function(a,b){M=b;try{var c=B(N()),d=N(),f=N();return dc(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&
g instanceof G||q(g),-g.v}},___syscall54:function(a,b){M=b;try{var c=xc(),d=N();switch(d){case 21509:case 21505:return c.tty?0:-E.M;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-E.M;case 21519:if(!c.tty)return-E.M;var f=N();return y[f>>2]=0;case 21520:return c.tty?-E.h:-E.M;case 21531:a=f=N();if(!c.f.Gb)throw new G(E.M);return c.f.Gb(c,d,a);case 21523:return c.tty?0:-E.M;default:q("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof FS&&g instanceof G||
q(g),-g.v}},___syscall6:function(a,b){M=b;try{var c=xc();fc(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof G||q(d),-d.v}},___syscall91:function(a,b){M=b;try{var c=N(),d=N(),f=wc[c];if(!f)return 0;if(d===f.fe){var g=Gb[f.fd],h=f.flags,k=new Uint8Array(A.subarray(c,c+d));g&&g.f.ia&&g.f.ia(g,k,0,d,h);wc[c]=null;f.tb&&R(f.ge)}return 0}catch(p){return"undefined"!==typeof FS&&p instanceof G||q(p),-p.v}},___unlock:function(){},__embind_register_bool:function(a,b,c,d,f){var g=yc(c);b=O(b);
Jc(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var d=x;else if(2===c)d=pa;else if(4===c)d=y;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},C:null})},__embind_register_emval:function(a,b){b=O(b);Jc(a,{name:b,fromWireType:function(a){var b=Q[a].value;4<a&&0===--Q[a].Lb&&(Q[a]=void 0,Kc.push(a));return b},toWireType:function(a,b){return Lc(b)},argPackAdvance:8,
readValueFromPointer:Mc,C:null})},__embind_register_float:function(a,b,c){c=yc(c);b=O(b);Jc(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Nc(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Oc(b,c),C:null})},__embind_register_function:function(a,b,c,d,f,g){var h=Tc(b,c);a=O(a);f=Uc(d,f);Sc(a,function(){Yc("Cannot call "+a+" due to unbound types",h)},b-1);Ic(h,function(c){var d=
[c[0],null].concat(c.slice(1)),h=c=a,k=f,w=d.length;2>w&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var T=null!==d[1]&&!1,C=!1,v=1;v<d.length;++v)if(null!==d[v]&&void 0===d[v].C){C=!0;break}var Ea="void"!==d[0].name,xa="",Ma="";for(v=0;v<w-2;++v)xa+=(0!==v?", ":"")+"arg"+v,Ma+=(0!==v?", ":"")+"arg"+v+"Wired";h="return function "+Dc(h)+"("+xa+") {\nif (arguments.length !== "+(w-2)+") {\nthrowBindingError('function "+h+" called with ' + arguments.length + ' arguments, expected "+
(w-2)+" args!');\n}\n";C&&(h+="var destructors = [];\n");var td=C?"destructors":"null";xa="throwBindingError invoker fn runDestructors retType classParam".split(" ");k=[P,k,g,Qc,d[0],d[1]];T&&(h+="var thisWired = classParam.toWireType("+td+", this);\n");for(v=0;v<w-2;++v)h+="var arg"+v+"Wired = argType"+v+".toWireType("+td+", arg"+v+"); // "+d[v+2].name+"\n",xa.push("argType"+v),k.push(d[v+2]);T&&(Ma="thisWired"+(0<Ma.length?", ":"")+Ma);h+=(Ea?"var rv = ":"")+"invoker(fn"+(0<Ma.length?", ":"")+Ma+
");\n";if(C)h+="runDestructors(destructors);\n";else for(v=T?1:2;v<d.length;++v)w=1===v?"thisWired":"arg"+(v-2)+"Wired",null!==d[v].C&&(h+=w+"_dtor("+w+"); // "+d[v].name+"\n",xa.push(w+"_dtor"),k.push(d[v].C));Ea&&(h+="var ret = retType.fromWireType(rv);\nreturn ret;\n");xa.push(h+"}\n");d=Pc(xa).apply(null,k);v=b-1;if(!e.hasOwnProperty(c))throw new Hc("Replacing nonexistant public symbol");void 0!==e[c].u&&void 0!==v?e[c].u[v]=d:(e[c]=d,e[c].ub=v);return[]})},__embind_register_integer:function(a,
b,c,d,f){function g(a){return a}b=O(b);-1===f&&(f=4294967295);var h=yc(c);if(0===d){var k=32-8*c;g=function(a){return a<<k>>>k}}var p=-1!=b.indexOf("unsigned");Jc(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+Nc(c)+'" to '+this.name);if(c<d||c>f)throw new TypeError('Passing a number "'+Nc(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return p?
c>>>0:c|0},argPackAdvance:8,readValueFromPointer:Zc(b,h,0!==d),C:null})},__embind_register_memory_view:function(a,b,c){function d(a){a>>=2;var b=D;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=O(c);Jc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Eb:!0})},__embind_register_std_string:function(a,b){b=O(b);Jc(a,{name:b,fromWireType:function(a){for(var b=D[a>>2],c=Array(b),g=0;g<b;++g)c[g]=
String.fromCharCode(A[a+4+g]);R(a);return c.join("")},toWireType:function(a,b){function c(a,b){return a[b]}function d(a,b){return a.charCodeAt(b)}b instanceof ArrayBuffer&&(b=new Uint8Array(b));var h;b instanceof Uint8Array?h=c:b instanceof Uint8ClampedArray?h=c:b instanceof Int8Array?h=c:"string"===typeof b?h=d:P("Cannot pass non-string to std::string");var k=b.length,p=wa(4+k);D[p>>2]=k;for(var r=0;r<k;++r){var t=h(b,r);255<t&&(R(p),P("String has UTF-16 code units that do not fit in 8 bits"));A[p+
4+r]=t}null!==a&&a.push(R,p);return p},argPackAdvance:8,readValueFromPointer:Mc,C:function(a){R(a)}})},__embind_register_std_wstring:function(a,b,c){c=O(c);if(2===b){var d=function(){return Fa};var f=1}else 4===b&&(d=function(){return D},f=2);Jc(a,{name:c,fromWireType:function(a){for(var b=d(),c=D[a>>2],g=Array(c),r=a+4>>f,t=0;t<c;++t)g[t]=String.fromCharCode(b[r+t]);R(a);return g.join("")},toWireType:function(a,c){var g=d(),h=c.length,r=wa(4+h*b);D[r>>2]=h;for(var t=r+4>>f,w=0;w<h;++w)g[t+w]=c.charCodeAt(w);
null!==a&&a.push(R,r);return r},argPackAdvance:8,readValueFromPointer:Mc,C:function(a){R(a)}})},__embind_register_void:function(a,b){b=O(b);Jc(a,{ee:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},_abort:function(){e.abort()},_emscripten_get_element_css_size:function(a,b,c){a?a?("number"==typeof a&&(a=B(a)),a="#window"==a?window:"#document"==a?document:"#screen"==a?window.screen:"#canvas"==a?e.canvas:"string"==typeof a?document.getElementById(a):a):a=window:a=e.canvas;
if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),ua[b>>3]=a.right-a.left,ua[c>>3]=a.bottom-a.top):(ua[b>>3]=a.clientWidth,ua[c>>3]=a.clientHeight);return 0},_emscripten_memcpy_big:function(a,b,c){A.set(A.subarray(b,b+c),a);return a},_emscripten_set_main_loop:Wd,_exit:function(a){e.exit(a)},_getenv:$d,_glActiveTexture:function(a){GLctx.activeTexture(a)},_glAttachShader:function(a,b){GLctx.attachShader(V[a],W[b])},_glBindAttribLocation:function(a,b,c){c=B(c);GLctx.bindAttribLocation(V[a],
b,c)},_glBindBuffer:function(a,b){var c=b?ce[b]:null;a==GLctx.ARRAY_BUFFER?fe=b:a==GLctx.ELEMENT_ARRAY_BUFFER&&(ge=b);GLctx.bindBuffer(a,c)},_glBindTexture:function(a,b){GLctx.bindTexture(a,b?de[b]:null)},_glBlendFunc:function(a,b){GLctx.blendFunc(a,b)},_glBufferData:function(a,b,c,d){c?GLctx.bufferData(a,A.subarray(c,c+b),d):GLctx.bufferData(a,b,d)},_glClear:function(a){GLctx.clear(a)},_glClearColor:function(a,b,c,d){GLctx.clearColor(a,b,c,d)},_glCompileShader:function(a){GLctx.compileShader(W[a])},
_glCompressedTexImage2D:function(a,b,c,d,f,g,h,k){GLctx.compressedTexImage2D(a,b,c,d,f,g,k?A.subarray(k,k+h):null)},_glCreateProgram:function(){var a=le(V),b=GLctx.createProgram();b.name=a;V[a]=b;return a},_glCreateShader:function(a){var b=le(W);W[b]=GLctx.createShader(a);return b},_glCullFace:function(a){GLctx.cullFace(a)},_glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],f=ce[d];f&&(GLctx.deleteBuffer(f),f.name=0,ce[d]=null,d==fe&&(fe=0),d==ge&&(ge=0))}},_glDeleteProgram:function(a){if(a){var b=
V[a];b?(GLctx.deleteProgram(b),b.name=0,V[a]=null,ie[a]=null):X(1281)}},_glDeleteShader:function(a){if(a){var b=W[a];b?(GLctx.deleteShader(b),W[a]=null):X(1281)}},_glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],f=de[d];f&&(GLctx.deleteTexture(f),f.name=0,de[d]=null)}},_glDepthFunc:function(a){GLctx.depthFunc(a)},_glDisable:function(a){GLctx.disable(a)},_glDrawElements:_glDrawElements,_glEnable:function(a){GLctx.enable(a)},_glEnableVertexAttribArray:function(a){S.ga[a].enabled=
!0;GLctx.enableVertexAttribArray(a)},_glFrontFace:function(a){GLctx.frontFace(a)},_glGenBuffers:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createBuffer();if(!d){for(X(1282);c<a;)y[b+4*c++>>2]=0;break}var f=le(ce);d.name=f;ce[f]=d;y[b+4*c>>2]=f}},_glGenTextures:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createTexture();if(!d){for(X(1282);c<a;)y[b+4*c++>>2]=0;break}var f=le(de);d.name=f;de[f]=d;y[b+4*c>>2]=f}},_glGetProgramInfoLog:function(a,b,c,d){a=GLctx.getProgramInfoLog(V[a]);null===a&&
(a="(unknown error)");0<b&&d?(b=Aa(a,A,d,b),c&&(y[c>>2]=b)):c&&(y[c>>2]=0)},_glGetProgramiv:function(a,b,c){if(c)if(a>=ae)X(1281);else{var d=ie[a];if(d)if(35716==b)a=GLctx.getProgramInfoLog(V[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b)y[c>>2]=d.Da;else if(35722==b){if(-1==d.W){a=V[a];var f=GLctx.getProgramParameter(a,GLctx.ACTIVE_ATTRIBUTES);for(b=d.W=0;b<f;++b)d.W=Math.max(d.W,GLctx.getActiveAttrib(a,b).name.length+1)}y[c>>2]=d.W}else if(35381==b){if(-1==d.X)for(a=V[a],
f=GLctx.getProgramParameter(a,GLctx.Wb),b=d.X=0;b<f;++b){var g=GLctx.ce(a,b);d.X=Math.max(d.X,g.length+1)}y[c>>2]=d.X}else y[c>>2]=GLctx.getProgramParameter(V[a],b);else X(1282)}else X(1281)},_glGetShaderInfoLog:function(a,b,c,d){a=GLctx.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");0<b&&d?(b=Aa(a,A,d,b),c&&(y[c>>2]=b)):c&&(y[c>>2]=0)},_glGetShaderiv:function(a,b,c){c?35716==b?(a=GLctx.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1):35720==b?(a=GLctx.getShaderSource(W[a]),
y[c>>2]=null===a||0==a.length?0:a.length+1):y[c>>2]=GLctx.getShaderParameter(W[a],b):X(1281)},_glGetUniformLocation:function(a,b){b=B(b);var c=0;if(-1!==b.indexOf("]",b.length-1)){var d=b.lastIndexOf("["),f=b.slice(d+1,-1);if(0<f.length&&(c=parseInt(f),0>c))return-1;b=b.slice(0,d)}a=ie[a];return a?(b=a.nb[b])&&c<b[0]?b[1]+c:-1:-1},_glIsBuffer:function(a){return(a=ce[a])?GLctx.isBuffer(a):0},_glIsTexture:function(a){return(a=de[a])?GLctx.isTexture(a):0},_glLinkProgram:function(a){GLctx.linkProgram(V[a]);
ie[a]=null;var b=V[a];ie[a]={nb:{},Da:0,W:-1,X:-1};a=ie[a];for(var c=a.nb,d=GLctx.getProgramParameter(b,GLctx.ACTIVE_UNIFORMS),f=0;f<d;++f){var g=GLctx.getActiveUniform(b,f),h=g.name;a.Da=Math.max(a.Da,h.length+1);-1!==h.indexOf("]",h.length-1)&&(h=h.slice(0,h.lastIndexOf("[")));var k=GLctx.getUniformLocation(b,h);if(null!=k){var p=le(ee);c[h]=[g.size,p];ee[p]=k;for(var r=1;r<g.size;++r)k=GLctx.getUniformLocation(b,h+"["+r+"]"),p=le(ee),ee[p]=k}}},_glPixelStorei:function(a,b){3333==a||3317==a&&(ke=
b);GLctx.pixelStorei(a,b)},_glShaderSource:function(a,b,c,d){for(var f="",g=0;g<b;++g){if(d){var h=y[d+4*g>>2];h=0>h?B(y[c+4*g>>2]):B(y[c+4*g>>2],h)}else h=B(y[c+4*g>>2]);f+=h}GLctx.shaderSource(W[a],f)},_glTexImage2D:function(a,b,c,d,f,g,h,k,p){var r=null;p&&(r=se(k,h,d,f,p));GLctx.texImage2D(a,b,c,d,f,g,h,k,r)},_glTexParameteri:function(a,b,c){GLctx.texParameteri(a,b,c)},_glUniform1f:function(a,b){GLctx.uniform1f(ee[a],b)},_glUniform4f:function(a,b,c,d,f){GLctx.uniform4f(ee[a],b,c,d,f)},_glUniformMatrix4fv:function(a,
b,c,d){if(256>=16*b){var f=ne[16*b-1];for(var g=0;g<16*b;g+=16)f[g]=z[d+4*g>>2],f[g+1]=z[d+(4*g+4)>>2],f[g+2]=z[d+(4*g+8)>>2],f[g+3]=z[d+(4*g+12)>>2],f[g+4]=z[d+(4*g+16)>>2],f[g+5]=z[d+(4*g+20)>>2],f[g+6]=z[d+(4*g+24)>>2],f[g+7]=z[d+(4*g+28)>>2],f[g+8]=z[d+(4*g+32)>>2],f[g+9]=z[d+(4*g+36)>>2],f[g+10]=z[d+(4*g+40)>>2],f[g+11]=z[d+(4*g+44)>>2],f[g+12]=z[d+(4*g+48)>>2],f[g+13]=z[d+(4*g+52)>>2],f[g+14]=z[d+(4*g+56)>>2],f[g+15]=z[d+(4*g+60)>>2]}else f=z.subarray(d>>2,d+64*b>>2);GLctx.uniformMatrix4fv(ee[a],
!!c,f)},_glUseProgram:function(a){GLctx.useProgram(a?V[a]:null)},_glVertexAttribPointer:function(a,b,c,d,f,g){var h=S.ga[a];fe?(h.ra=!1,GLctx.vertexAttribPointer(a,b,c,!!d,f,g)):(h.size=b,h.type=c,h.fb=d,h.Ia=f,h.ja=g,h.ra=!0)},_glViewport:function(a,b,c,d){GLctx.viewport(a,b,c,d)},_glfwCreateWindow:function(a,b,c,d){var f;for(f=0;f<Y.length&&null!==Y[f];f++);if(0<f)throw"glfwCreateWindow only supports one window at time currently";var g=f+1;if(0>=a||0>=b)g=0;else{d?Pe():Td(a,b);for(f=0;f<Y.length&&
null==Y[f];f++);f==Y.length&&(e.K=xd(e.canvas,!0,!0,{antialias:1<ue[135181],depth:0<ue[135173],stencil:0<ue[135174],alpha:0<ue[135172]}));e.K?(a=new te(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,Z=a,g=a.id):g=0}return g},_glfwDestroyWindow:function(a){a:{if(a=ve(a)){a.ob&&e.dynCall_vi(a.ob,a.id);Y[a.id-1]=null;Z.id==a.id&&(Z=null);for(a=0;a<Y.length;a++)if(null!==Y[a]){a=void 0;break a}e.K=void 0}a=void 0}return a},_glfwGetCursorPos:function(a,b,c){u(b,Md,"double");u(c,Nd,"double")},_glfwGetTime:function(){return Vd()/
1E3-we},_glfwGetVersion:function(a,b,c){u(a,3,"i32");u(b,2,"i32");u(c,1,"i32")},_glfwGetWindowSize:function(a,b,c){var d=0,f=0;if(a=ve(a))d=a.width,f=a.height;u(b,d,"i32");u(c,f,"i32")},_glfwInit:function(){if(Y)return 1;we=Vd()/1E3;ue=xe;Y=[];Z=null;window.addEventListener("gamepadconnected",Ce,!0);window.addEventListener("gamepaddisconnected",Ee,!0);window.addEventListener("keydown",Fe,!0);window.addEventListener("keypress",Ae,!0);window.addEventListener("keyup",Ge,!0);window.addEventListener("blur",
He,!0);e.canvas.addEventListener("touchmove",Ie,!0);e.canvas.addEventListener("touchstart",Me,!0);e.canvas.addEventListener("touchcancel",Ne,!0);e.canvas.addEventListener("touchend",Ne,!0);e.canvas.addEventListener("mousemove",Ie,!0);e.canvas.addEventListener("mousedown",Me,!0);e.canvas.addEventListener("mouseup",Ne,!0);e.canvas.addEventListener("wheel",Oe,!0);e.canvas.addEventListener("mousewheel",Oe,!0);e.canvas.addEventListener("mouseenter",Je,!0);e.canvas.addEventListener("mouseleave",Ke,!0);
e.canvas.addEventListener("drop",Te,!0);e.canvas.addEventListener("dragover",Ue,!0);Sd.push(function(a,b){if(Z){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Z.kb=Z.x,Z.lb=Z.y,Z.jb=Z.width,Z.ib=Z.height,Z.x=Z.y=0,Z.width=screen.width,Z.height=screen.height,Z.za=!0):1==Z.za?(Z.x=Z.kb,Z.y=Z.lb,Z.width=Z.jb,Z.height=Z.ib,Z.za=!1):Z.width!=a||Z.height!=b?(Z.width=a,Z.height=b):c=!1;c&&(Td(Z.width,Z.height,!0),Z&&Z.Ja&&e.dynCall_viii(Z.Ja,Z.id,
Z.width,Z.height),Z&&Z.ya&&e.dynCall_viii(Z.ya,Z.id,Z.width,Z.height))}});return 1},_glfwMakeContextCurrent:function(){},_glfwPollEvents:function(){},_glfwSetCursorEnterCallback:function(a,b){if(a=ve(a))a.V=b},_glfwSetCursorPosCallback:function(a,b){if(a=ve(a))a.sa=b},_glfwSetFramebufferSizeCallback:function(a,b){if(a=ve(a))a.ya=b},_glfwSetKeyCallback:function(a,b){if(a=ve(a))a.Ba=b},_glfwSetMouseButtonCallback:function(a,b){if(a=ve(a))a.Ea=b},_glfwSetWindowSizeCallback:function(a,b){if(a=ve(a))a.Ja=
b},_glfwSwapBuffers:function(){},_glfwTerminate:function(){window.removeEventListener("gamepadconnected",Ce,!0);window.removeEventListener("gamepaddisconnected",Ee,!0);window.removeEventListener("keydown",Fe,!0);window.removeEventListener("keypress",Ae,!0);window.removeEventListener("keyup",Ge,!0);window.removeEventListener("blur",He,!0);e.canvas.removeEventListener("touchmove",Ie,!0);e.canvas.removeEventListener("touchstart",Me,!0);e.canvas.removeEventListener("touchcancel",Ne,!0);e.canvas.removeEventListener("touchend",
Ne,!0);e.canvas.removeEventListener("mousemove",Ie,!0);e.canvas.removeEventListener("mousedown",Me,!0);e.canvas.removeEventListener("mouseup",Ne,!0);e.canvas.removeEventListener("wheel",Oe,!0);e.canvas.removeEventListener("mousewheel",Oe,!0);e.canvas.removeEventListener("mouseenter",Je,!0);e.canvas.removeEventListener("mouseleave",Ke,!0);e.canvas.removeEventListener("drop",Te,!0);e.canvas.removeEventListener("dragover",Ue,!0);e.canvas.width=e.canvas.height=1;Z=Y=null},_glfwWindowHint:function(a,b){ue[a]=
b},_pthread_cond_wait:function(){return 0},_pthread_getspecific:function(a){return Ve[a]||0},_pthread_key_create:function(a){if(0==a)return E.h;y[a>>2]=We;Ve[We]=0;We++;return 0},_pthread_once:Xe,_pthread_setspecific:function(a,b){if(!(a in Ve))return E.h;Ve[a]=b;return 0},_strftime_l:function(a,b,c,d){return cf(a,b,c,d)},DYNAMICTOP_PTR:Na,STACKTOP:Ja};var uf=e.asm(e.vb,e.wb,buffer);e.asm=uf;
var eb=e.__GLOBAL__I_000101=function(){return e.asm.__GLOBAL__I_000101.apply(null,arguments)},fb=e.__GLOBAL__sub_I_XenepicRes_cpp=function(){return e.asm.__GLOBAL__sub_I_XenepicRes_cpp.apply(null,arguments)},hb=e.__GLOBAL__sub_I_bind_cpp=function(){return e.asm.__GLOBAL__sub_I_bind_cpp.apply(null,arguments)},ib=e.__GLOBAL__sub_I_iostream_cpp=function(){return e.asm.__GLOBAL__sub_I_iostream_cpp.apply(null,arguments)},gb=e.__GLOBAL__sub_I_main_cpp=function(){return e.asm.__GLOBAL__sub_I_main_cpp.apply(null,
arguments)};e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};var Xc=e.___getTypeName=function(){return e.asm.___getTypeName.apply(null,arguments)},R=e._free=function(){return e.asm._free.apply(null,arguments)};e._main=function(){return e.asm._main.apply(null,arguments)};var wa=e._malloc=function(){return e.asm._malloc.apply(null,arguments)},Da=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)};
e.dynCall_i=function(){return e.asm.dynCall_i.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.dynCall_ii.apply(null,arguments)};e.dynCall_iii=function(){return e.asm.dynCall_iii.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};e.dynCall_iiiii=function(){return e.asm.dynCall_iiiii.apply(null,arguments)};e.dynCall_iiiiid=function(){return e.asm.dynCall_iiiiid.apply(null,arguments)};
e.dynCall_iiiiii=function(){return e.asm.dynCall_iiiiii.apply(null,arguments)};e.dynCall_iiiiiid=function(){return e.asm.dynCall_iiiiiid.apply(null,arguments)};e.dynCall_iiiiiii=function(){return e.asm.dynCall_iiiiiii.apply(null,arguments)};e.dynCall_iiiiiiii=function(){return e.asm.dynCall_iiiiiiii.apply(null,arguments)};e.dynCall_iiiiiiiii=function(){return e.asm.dynCall_iiiiiiiii.apply(null,arguments)};e.dynCall_iiiiij=function(){return e.asm.dynCall_iiiiij.apply(null,arguments)};
e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.dynCall_vidd=function(){return e.asm.dynCall_vidd.apply(null,arguments)};e.dynCall_vii=function(){return e.asm.dynCall_vii.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.dynCall_viii.apply(null,arguments)};e.dynCall_viiii=function(){return e.asm.dynCall_viiii.apply(null,arguments)};
e.dynCall_viiiii=function(){return e.asm.dynCall_viiiii.apply(null,arguments)};e.dynCall_viiiiii=function(){return e.asm.dynCall_viiiiii.apply(null,arguments)};e.dynCall_viijii=function(){return e.asm.dynCall_viijii.apply(null,arguments)};e.asm=uf;e.getMemory=function(a){if(ja)if(Xa)var b=wa(a);else{assert(Na);b=y[Na>>2];a=b+a+15&-16;y[Na>>2]=a;if(a=a>=Pa)Oa(),a=!0;a&&(y[Na>>2]=b,b=0)}else b=ia(a);return b};e.addRunDependency=bb;e.removeRunDependency=cb;e.FS_createFolder=mc;e.FS_createPath=nc;
e.FS_createDataFile=pc;e.FS_createPreloadedFile=tc;e.FS_createLazyFile=sc;e.FS_createLink=qc;e.FS_createDevice=L;e.FS_unlink=bc;function ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ha.prototype=Error();ha.prototype.constructor=ha;ab=function vf(){e.calledRun||wf();e.calledRun||(ab=vf)};
e.callMain=function(a){a=a||[];Xa||(Xa=!0,Ra(Ta));var b=a.length+1,c=Da(4*(b+1));y[c>>2]=Ca(e.thisProgram);for(var d=1;d<b;d++)y[(c>>2)+d]=Ca(a[d-1]);y[(c>>2)+b]=0;try{var f=e._main(b,c,0);xf(f,!0)}catch(g){g instanceof ha||("SimulateInfiniteLoop"==g?e.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),e.printErr("exception thrown: "+a),e.quit(1,g)))}finally{}};
function wf(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!oa)){Xa||(Xa=!0,Ra(Ta));Ra(Ua);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&yf&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Wa.unshift(b)}Ra(Wa)}}a=a||e.arguments;if(!(0<Za)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ya();Ra(Sa);0<Za||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);b()},1)):b())}}e.run=wf;function xf(a,b){if(!b||!e.noExitRuntime||0!==a){if(!e.noExitRuntime&&(oa=!0,Ja=void 0,Ra(Va),e.onExit))e.onExit(a);m&&process.exit(a);e.quit(a,new ha(a))}}e.exit=xf;function q(a){if(e.onAbort)e.onAbort(a);void 0!==a?(e.print(a),e.printErr(a),a=JSON.stringify(a)):a="";oa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=q;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var yf=!0;
e.noInitialRun&&(yf=!1);e.noExitRuntime=!0;wf();
