var e;e||(e=typeof Module !== 'undefined' ? Module : {});e.ta||(e.ta=0,e.xb=0);e.ta++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var f=b;c.total&&(f=c.total);if(c.loaded){d.j?e.L[a].loaded=c.loaded:(d.j=!0,e.L||(e.L={}),e.L[a]={loaded:c.loaded,total:f});var g=f=c=0,h;for(h in e.L){var n=e.L[h];c+=n.total;f+=n.loaded;g++}c=Math.ceil(c*e.ta/g);e.setStatus&&e.setStatus("Downloading data... ("+f+"/"+c+")")}else!e.L&&e.setStatus&&e.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(){function b(a,b,c,d){this.start=a;this.end=b;this.wb=c;this.audio=d}function c(c){e.xb++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);e.SPLIT_MEMORY&&e.printErr("warning: you should run the file packager with --no-heap-copy when SPLIT_MEMORY is used, otherwise copying into the heap may fail due to the splitting");
var d=e.getMemory(c.length);e.HEAPU8.set(c,d);b.prototype.ub=e.HEAPU8.subarray(d,d+c.length);c=a.files;for(d=0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();e.removeRunDependency("datafile_./Web/pharaoh.data")}e.FS_createPath("/","pharaoh-gm",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;e.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.ub.subarray(this.start,this.end))},finish:function(a){e.FS_createDataFile(this.name,null,
a,!0,!0,!0);e.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,f=0;f<d.length;++f)(new b(d[f].start,d[f].end,d[f].wb,d[f].audio)).open("GET",d[f].filename);e.addRunDependency("datafile_./Web/pharaoh.data");e.cb||(e.cb={});e.cb["./Web/pharaoh.data"]={Xd:!1};h?(c(h),h=null):g=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,e.printErr("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var d="function"===typeof e.locateFile?e.locateFile("pharaoh.data"):(e.filePackagePrefixURL||"")+"pharaoh.data",f=a.ee,g=null,h=e.getPreloadedPackage?
e.getPreloadedPackage(d,f):null;h||b(d,f,function(a){g?(g(a),g=null):h=a});e.calledRun?c():(e.preRun||(e.preRun=[]),e.preRun.push(c))})({files:[{audio:0,start:0,crunched:0,end:6148,filename:"/pharaoh-gm/.DS_Store"},{audio:0,start:6148,crunched:0,end:45525,filename:"/pharaoh-gm/00000000.gm"},{audio:0,start:45525,crunched:0,end:46293,filename:"/pharaoh-gm/00000000.tt"},{audio:0,start:46293,crunched:0,end:82747,filename:"/pharaoh-gm/00000001.gm"},{audio:0,start:82747,crunched:0,end:153143,filename:"/pharaoh-gm/00000002.gm"},
{audio:0,start:153143,crunched:0,end:155275,filename:"/pharaoh-gm/0000000A.gm"},{audio:0,start:155275,crunched:0,end:228893,filename:"/pharaoh-gm/0000000A.tt"}],remote_package_size:228893,package_uuid:"5c563b43-4d71-4734-a450-eb1b44e08119"});var aa={},k;for(k in e)e.hasOwnProperty(k)&&(aa[k]=e[k]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var ba=!1,l=!1,m=!1,ca=!1;
if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)ba=!0;else if("WORKER"===e.ENVIRONMENT)l=!0;else if("NODE"===e.ENVIRONMENT)m=!0;else if("SHELL"===e.ENVIRONMENT)ca=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else ba="object"===typeof window,l="function"===typeof importScripts,m="object"===typeof process&&"function"===typeof require&&!ba&&!l,ca=!ba&&!m&&!l;
if(m){var da,ea;e.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;});process.on("unhandledRejection",
function(){process.exit(1)});e.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ba||l)e.read=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},"undefined"!=typeof arguments&&(e.arguments=arguments),e.setWindowTitle=
function(a){document.title=a};e.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;e.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||e.print;e.print=e.print;e.printErr=e.printErr;for(k in aa)aa.hasOwnProperty(k)&&(e[k]=aa[k]);aa=void 0;function ha(a){assert(!ia);var b=q;q=q+a+15&-16;return b}function ja(a){var b;b||(b=16);return Math.ceil(a/b)*b}
function ka(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:return"*"===a[a.length-1]?4:"i"===a[0]?(a=parseInt(a.substr(1)),assert(0===a%8),a/8):0}}function la(a){ma||(ma={});ma[a]||(ma[a]=1,e.printErr(a))}var ma,na=0;function assert(a,b){a||t("Assertion failed: "+b)}
function v(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":w[a>>0]=b;break;case "i8":w[a>>0]=b;break;case "i16":oa[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":tempI64=[b>>>0,(tempDouble=b,1<=+pa(tempDouble)?0<tempDouble?(ra(+sa(tempDouble/4294967296),4294967295)|0)>>>0:~~+ta((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];x[a>>2]=tempI64[0];x[a+4>>2]=tempI64[1];break;case "float":y[a>>2]=b;break;case "double":ua[a>>3]=b;break;default:t("invalid type for setValue: "+
c)}}function va(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;var f="string"===typeof b?b:null;var g=("function"===typeof wa?wa:ha)(Math.max(d,f?1:b.length));if(c){a=g;assert(0==(g&3));for(b=g+(d&-4);a<b;a+=4)x[a>>2]=0;for(b=g+d;a<b;)w[a++>>0]=0;return g}if("i8"===f)return a.subarray||a.slice?z.set(a,g):z.set(new Uint8Array(a),g),g;c=0;for(var h,n,p;c<d;){var r=a[c];h=f||b[c];0===h?c++:("i64"==h&&(h="i32"),v(g+c,r,h),p!==h&&(n=ka(h),p=h),c+=n)}return g}
function A(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=z[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,z.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return xa(z,a)}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function xa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var n=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|n;else{var p=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|n<<6|p}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function za(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=128|
h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}function Aa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ba(a){var b=Aa(a)+1,c=Ca(b);za(a,w,c,b);return c}var buffer,w,z,oa,Da,x,Ea,y,ua;
function Fa(){e.HEAP8=w=new Int8Array(buffer);e.HEAP16=oa=new Int16Array(buffer);e.HEAP32=x=new Int32Array(buffer);e.HEAPU8=z=new Uint8Array(buffer);e.HEAPU16=Da=new Uint16Array(buffer);e.HEAPU32=Ea=new Uint32Array(buffer);e.HEAPF32=y=new Float32Array(buffer);e.HEAPF64=ua=new Float64Array(buffer)}var Ga,q,ia,Ha,Ia,Ja,Ka,C;Ga=q=Ha=Ia=Ja=Ka=C=0;ia=!1;
function La(){t("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+D+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ma=e.TOTAL_STACK||5242880,D=e.TOTAL_MEMORY||16777216;D<Ma&&e.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+D+"! (TOTAL_STACK="+Ma+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:D/65536,maximum:D/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(D),e.buffer=buffer);Fa();x[0]=1668509029;oa[1]=25459;if(115!==z[2]||99!==z[3])throw"Runtime error: expected the system to be little-endian!";
function Na(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.ea;"number"===typeof c?void 0===b.$?e.dynCall_v(c):e.dynCall_vi(c,b.$):c(void 0===b.$?null:b.$)}}}var Oa=[],Pa=[],Qa=[],Ra=[],Sa=[],Ta=!1;function Ua(){var a=e.preRun.shift();Oa.unshift(a)}var pa=Math.abs,ta=Math.ceil,sa=Math.floor,ra=Math.min,Va=0,Wa=null,Xa=null;function Ya(){Va++;e.monitorRunDependencies&&e.monitorRunDependencies(Va)}
function Za(){Va--;e.monitorRunDependencies&&e.monitorRunDependencies(Va);if(0==Va&&(null!==Wa&&(clearInterval(Wa),Wa=null),Xa)){var a=Xa;Xa=null;a()}}e.preloadedImages={};e.preloadedAudios={};function $a(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(u){t(u)}}function b(){return e.wasmBinary||!ba&&!l||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){n=a.exports;if(n.memory){a=n.memory;var b=e.buffer;a.byteLength<b.byteLength&&e.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Fa()}e.asm=n;e.usingWasm=!0;Za()}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){e.printErr("failed to asynchronously prepare wasm: "+
a);t(a)})}if("object"!==typeof WebAssembly)return e.printErr("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return e.printErr("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;Ya();if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(V){return e.printErr("Module.instantiateWasm callback failed with error: "+V),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
$a(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d).catch(function(a){e.printErr("wasm streaming compile failed: "+a);e.printErr("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="pharaoh.wast",f="pharaoh.wasm",g="pharaoh.temp.asm.js";"function"===typeof e.locateFile&&($a(d)||(d=e.locateFile(d)),$a(f)||(f=e.locateFile(f)),$a(g)||(g=e.locateFile(g)));var h={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%
b},"debugger":function(){debugger}},parent:e},n=null;e.asmPreload=e.asm;var p=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===r)var b=p(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(E){b=null;break a}b=void 0}return b};var r="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&
"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);(b=c(b))||t("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();Ga=1024;q=Ga+41616;
Pa.push({ea:function(){ab()}},{ea:function(){bb()}},{ea:function(){cb()}});e.STATIC_BASE=Ga;e.STATIC_BUMP=41616;q+=16;function db(){return!!db.j}
var F={G:1,A:2,Ed:3,zc:4,F:5,Ka:6,Sb:7,Xc:8,Y:9,fc:10,Ga:11,Od:11,ob:12,la:13,sc:14,kd:15,ma:16,Ha:17,Pd:18,oa:19,Ia:20,R:21,h:22,Sc:23,nb:24,K:25,Ld:26,tc:27,ed:28,Z:29,Bd:30,Lc:31,ud:32,pc:33,yd:34,ad:42,wc:43,hc:44,Cc:45,Dc:46,Ec:47,Kc:48,Md:49,Vc:50,Bc:51,mc:35,Yc:37,Yb:52,ac:53,Qd:54,Tc:55,bc:56,cc:57,nc:35,dc:59,hd:60,Wc:61,Id:62,gd:63,bd:64,cd:65,Ad:66,Zc:67,Vb:68,Fd:69,ic:70,vd:71,Nc:72,qc:73,$b:74,pd:76,Zb:77,zd:78,Fc:79,Gc:80,Jc:81,Ic:82,Hc:83,jd:38,Ja:39,Oc:36,na:40,qd:95,td:96,lc:104,
Uc:105,Wb:97,xd:91,nd:88,dd:92,Cd:108,kc:111,Tb:98,jc:103,Rc:101,Pc:100,Jd:110,uc:112,vc:113,yc:115,Xb:114,oc:89,Mc:90,wd:93,Dd:94,Ub:99,Qc:102,Ac:106,ld:107,Kd:109,Nd:87,rc:122,Gd:116,od:95,$c:123,xc:84,rd:75,ec:125,md:131,sd:130,Hd:86};function eb(a){e.___errno_location&&(x[e.___errno_location()>>2]=a);return a}
var fb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",
24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",
44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",
65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",
82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",
100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",
122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function gb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function hb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ib(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function jb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function kb(){var a=Array.prototype.slice.call(arguments,0);return hb(a.join("/"))}function G(a,b){return hb(a+"/"+b)}
function lb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var mb=[];function nb(a,b){mb[a]={input:[],output:[],N:b};ob(a,pb)}
var pb={open:function(a){var b=mb[a.node.rdev];if(!b)throw new H(F.oa);a.tty=b;a.seekable=!1},close:function(a){a.tty.N.flush(a.tty)},flush:function(a){a.tty.N.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.N.Ua)throw new H(F.Ka);for(var f=0,g=0;g<d;g++){try{var h=a.tty.N.Ua(a.tty)}catch(n){throw new H(F.F);}if(void 0===h&&0===f)throw new H(F.Ga);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.N.Da)throw new H(F.Ka);
for(var f=0;f<d;f++)try{a.tty.N.Da(a.tty,b[c+f])}catch(g){throw new H(F.F);}d&&(a.node.timestamp=Date.now());return f}},rb={Ua:function(a){if(!a.input.length){var b=null;if(m){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=qb(b,!0)}return a.input.shift()},Da:function(a,b){null===b||10===b?(e.print(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(e.print(xa(a.output,0)),a.output=[])}},sb={Da:function(a,b){null===b||10===b?(e.printErr(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(e.printErr(xa(a.output,0)),a.output=[])}},I={s:null,m:function(){return I.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(F.G);I.s||(I.s={dir:{node:{v:I.c.v,l:I.c.l,lookup:I.c.lookup,U:I.c.U,rename:I.c.rename,unlink:I.c.unlink,rmdir:I.c.rmdir,readdir:I.c.readdir,symlink:I.c.symlink},stream:{B:I.f.B}},file:{node:{v:I.c.v,l:I.c.l},stream:{B:I.f.B,read:I.f.read,write:I.f.write,La:I.f.La,Za:I.f.Za,ga:I.f.ga}},link:{node:{v:I.c.v,
l:I.c.l,readlink:I.c.readlink},stream:{}},Pa:{node:{v:I.c.v,l:I.c.l},stream:tb}});c=ub(a,b,c,d);J(c.mode)?(c.c=I.s.dir.node,c.f=I.s.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=I.s.file.node,c.f=I.s.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=I.s.link.node,c.f=I.s.link.stream):8192===(c.mode&61440)&&(c.c=I.s.Pa.node,c.f=I.s.Pa.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},zb:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},Zd:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array},Qa:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=I.zb(a),a.g=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Hb:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{v:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.H=4096;b.blocks=Math.ceil(b.size/b.H);return b},
l:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.Hb(a,b.size)},lookup:function(){throw vb[F.A];},U:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(J(a.mode)){try{var d=wb(b,c)}catch(g){}if(d)for(var f in d.b)throw new H(F.Ja);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=wb(a,b),d;for(d in c.b)throw new H(F.Ja);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(F.h);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.g=d;if(0===a.g&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.g=d;if(f+d<=a.g)return a.b.set(b.subarray(c,c+d),f),d}I.Qa(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.g=Math.max(a.g,f+d);return d},B:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new H(F.h);return b},La:function(a,b,c){I.Qa(a.node,b+c);a.node.g=Math.max(a.node.g,
b+c)},Za:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new H(F.oa);c=a.node.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.g)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=wa(d);if(!d)throw new H(F.ob);b.set(c,d)}else a=!1,d=c.byteOffset;return{ha:d,rb:a}},ga:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new H(F.oa);if(f&2)return 0;I.f.write(a,b,0,d,c,!1);return 0}}},K={fa:!1,Kb:function(){K.fa=!!process.platform.match(/^win/);
var a=process.binding("constants");a.fs&&(a=a.fs);K.Ra={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Ma:function(a){return Buffer.j?Buffer.from(a):new Buffer(a)},m:function(a){assert(m);return K.createNode(null,"/",K.Ta(a.Ca.root),0)},createNode:function(a,b,c){if(!J(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new H(F.h);a=ub(a,b,c);a.c=K.c;a.f=K.f;return a},Ta:function(a){try{var b=fs.lstatSync(a);K.fa&&(b.mode=b.mode|(b.mode&292)>>
2)}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}return b.mode},o:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.m.Ca.root);b.reverse();return kb.apply(null,b)},yb:function(a){a&=-2656257;var b=0,c;for(c in K.Ra)a&c&&(b|=K.Ra[c],a^=c);if(a)throw new H(F.h);return b},c:{v:function(a){a=K.o(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}K.fa&&!b.H&&(b.H=4096);K.fa&&!b.blocks&&(b.blocks=(b.size+b.H-1)/b.H|0);return{dev:b.dev,ino:b.ino,
mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,H:b.H,blocks:b.blocks}},l:function(a,b){var c=K.o(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new H(F[d.code]);}},lookup:function(a,b){var c=G(K.o(a),b);c=K.Ta(c);return K.createNode(a,b,c)},U:function(a,b,c,d){a=K.createNode(a,b,c,d);b=K.o(a);try{J(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,
"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new H(F[f.code]);}return a},rename:function(a,b,c){a=K.o(a);b=G(K.o(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new H(F[d.code]);}},unlink:function(a,b){a=G(K.o(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}},rmdir:function(a,b){a=G(K.o(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}},readdir:function(a){a=K.o(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;
throw new H(F[b.code]);}},symlink:function(a,b,c){a=G(K.o(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new H(F[d.code]);}},readlink:function(a){var b=K.o(a);try{return b=fs.readlinkSync(b),b=xb.relative(xb.resolve(a.m.Ca.root),b)}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}}},f:{open:function(a){var b=K.o(a.node);try{32768===(a.node.mode&61440)&&(a.W=fs.openSync(b,K.yb(a.flags)))}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}},close:function(a){try{32768===(a.node.mode&
61440)&&a.W&&fs.closeSync(a.W)}catch(b){if(!b.code)throw b;throw new H(F[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.W,K.Ma(b.buffer),c,d,f)}catch(g){throw new H(F[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.W,K.Ma(b.buffer),c,d,f)}catch(g){throw new H(F[g.code]);}},B:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.W).size}catch(d){throw new H(F[d.code]);}if(0>b)throw new H(F.h);return b}}};
q+=16;q+=16;q+=16;var yb=null,zb={},L=[],Ab=1,Bb=null,Cb=!0,Db={},H=null,vb={};
function M(a,b){a=lb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Sa:!0,Ea:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ea)throw new H(F.na);a=gb(a.split("/").filter(function(a){return!!a}),!1);var f=yb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=wb(f,a[d]);c=G(c,a[d]);f.V&&(!g||g&&b.Sa)&&(f=f.V.root);if(!g||b.ua)for(g=0;40960===(f.mode&61440);)if(f=Eb(c),c=lb(ib(c),f),f=M(c,{Ea:b.Ea}).node,40<g++)throw new H(F.na);}return{path:c,node:f}}
function Fb(a){for(var b;;){if(a===a.parent)return a=a.m.$a,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Gb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Bb.length}function Hb(a){var b=Gb(a.parent.id,a.name);a.M=Bb[b];Bb[b]=a}function wb(a,b){var c;if(c=(c=Ib(a,"x"))?c:a.c.lookup?0:F.la)throw new H(c,a);for(c=Bb[Gb(a.id,b)];c;c=c.M){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function ub(a,b,c,d){Jb||(Jb=function(a,b,c,d){a||(a=this);this.parent=a;this.m=a.m;this.V=null;this.id=Ab++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},Jb.prototype={},Object.defineProperties(Jb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Eb:{get:function(){return J(this.mode)}},Db:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Jb(a,b,c,d);Hb(a);return a}function J(a){return 16384===(a&61440)}var Kb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Lb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ib(a,b){if(Cb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return F.la}else return F.la;return 0}
function Mb(a,b){try{return wb(a,b),F.Ha}catch(c){}return Ib(a,"wx")}function Nb(a){var b=4096;for(a=a||0;a<=b;a++)if(!L[a])return a;throw new H(F.nb);}function Ob(a,b){Pb||(Pb=function(){},Pb.prototype={},Object.defineProperties(Pb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Pb,d;for(d in a)c[d]=a[d];a=c;b=Nb(b);a.fd=b;return L[b]=a}var tb={open:function(a){a.f=zb[a.node.rdev].f;a.f.open&&a.f.open(a)},B:function(){throw new H(F.Z);}};
function ob(a,b){zb[a]={f:b}}function Rb(a,b){var c="/"===b,d=!b;if(c&&yb)throw new H(F.ma);if(!c&&!d){var f=M(b,{Sa:!1});b=f.path;f=f.node;if(f.V)throw new H(F.ma);if(!J(f.mode))throw new H(F.Ia);}b={type:a,Ca:{},$a:b,Fb:[]};a=a.m(b);a.m=b;b.root=a;c?yb=a:f&&(f.V=b,f.m&&f.m.Fb.push(b))}function Sb(a,b,c){var d=M(a,{parent:!0}).node;a=jb(a);if(!a||"."===a||".."===a)throw new H(F.h);var f=Mb(d,a);if(f)throw new H(f);if(!d.c.U)throw new H(F.G);return d.c.U(d,a,b,c)}
function N(a,b){return Sb(a,(void 0!==b?b:511)&1023|16384,0)}function Tb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Sb(a,b|8192,c)}function Ub(a,b){if(!lb(a))throw new H(F.A);var c=M(b,{parent:!0}).node;if(!c)throw new H(F.A);b=jb(b);var d=Mb(c,b);if(d)throw new H(d);if(!c.c.symlink)throw new H(F.G);return c.c.symlink(c,b,a)}
function Vb(a){var b=M(a,{parent:!0}).node,c=jb(a),d=wb(b,c);a:{try{var f=wb(b,c)}catch(h){f=h.u;break a}var g=Ib(b,"wx");f=g?g:J(f.mode)?F.R:0}if(f)throw new H(f);if(!b.c.unlink)throw new H(F.G);if(d.V)throw new H(F.ma);try{Db.willDeletePath&&Db.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.c.unlink(b,c);b=Gb(d.parent.id,d.name);if(Bb[b]===d)Bb[b]=d.M;else for(b=Bb[b];b;){if(b.M===d){b.M=d.M;break}b=b.M}try{if(Db.onDeletePath)Db.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Eb(a){a=M(a).node;if(!a)throw new H(F.A);if(!a.c.readlink)throw new H(F.h);return lb(Fb(a.parent),a.c.readlink(a))}function Wb(a,b){var c;"string"===typeof a?c=M(a,{ua:!0}).node:c=a;if(!c.c.l)throw new H(F.G);c.c.l(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Xb(a,b,c,d){if(""===a)throw new H(F.A);if("string"===typeof b){var f=Kb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=hb(a);try{g=M(a,{ua:!(b&131072)}).node}catch(n){}}f=!1;if(b&64)if(g){if(b&128)throw new H(F.Ha);}else g=Sb(a,c,0),f=!0;if(!g)throw new H(F.A);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!J(g.mode))throw new H(F.Ia);if(!f&&(c=g?40960===(g.mode&61440)?F.na:
J(g.mode)&&("r"!==Lb(b)||b&512)?F.R:Ib(g,Lb(b)):F.A))throw new H(c);if(b&512){c=g;var h;"string"===typeof c?h=M(c,{ua:!0}).node:h=c;if(!h.c.l)throw new H(F.G);if(J(h.mode))throw new H(F.R);if(32768!==(h.mode&61440))throw new H(F.h);if(c=Ib(h,"w"))throw new H(c);h.c.l(h,{size:0,timestamp:Date.now()})}b&=-641;d=Ob({node:g,path:Fb(g),flags:b,seekable:!0,position:0,f:g.f,Pb:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(Yb||(Yb={}),a in Yb||(Yb[a]=1,e.printErr("read file: "+a)));try{Db.onOpenFile&&
(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Db.onOpenFile(a,g))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function Zb(a){a.ya&&(a.ya=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{L[a.fd]=null}}function $b(a,b,c){if(!a.seekable||!a.f.B)throw new H(F.Z);a.position=a.f.B(a,b,c);a.Pb=[]}
function ac(a,b,c,d,f,g){if(0>d||0>f)throw new H(F.h);if(0===(a.flags&2097155))throw new H(F.Y);if(J(a.node.mode))throw new H(F.R);if(!a.f.write)throw new H(F.h);a.flags&1024&&$b(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new H(F.Z);b=a.f.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&Db.onWriteToFile)Db.onWriteToFile(a.path)}catch(n){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+n.message)}return b}
function bc(){H||(H=function(a,b){this.node=b;this.Jb=function(a){this.u=a;for(var b in F)if(F[b]===a){this.code=b;break}};this.Jb(a);this.message=fb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},H.prototype=Error(),H.prototype.constructor=H,[F.A].forEach(function(a){vb[a]=new H(a);vb[a].stack="<generic error, no stack>"}))}var cc;function dc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function ec(a,b,c,d){a=G("string"===typeof a?a:Fb(a),b);return N(a,dc(c,d))}function fc(a,b){a="string"===typeof a?a:Fb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a,c);try{N(d)}catch(f){}a=d}}return d}function hc(a,b,c,d){a=G("string"===typeof a?a:Fb(a),b);c=dc(c,d);return Sb(a,(void 0!==c?c:438)&4095|32768,0)}
function ic(a,b,c,d,f,g){a=b?G("string"===typeof a?a:Fb(a),b):a;d=dc(d,f);f=Sb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Wb(f,d|146);a=Xb(f,"w");ac(a,c,0,c.length,0,g);Zb(a);Wb(f,d)}return f}
function O(a,b,c,d){a=G("string"===typeof a?a:Fb(a),b);b=dc(!!c,!!d);O.Xa||(O.Xa=64);var f=O.Xa++<<8|0;ob(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,h=0;h<f;h++){try{var n=c()}catch(qa){throw new H(F.F);}if(void 0===n&&0===g)throw new H(F.Ga);if(null===n||void 0===n)break;g++;b[d+h]=n}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(u){throw new H(F.F);}f&&(a.node.timestamp=
Date.now());return g}});return Tb(a,b,f)}function jc(a,b,c){a=G("string"===typeof a?a:Fb(a),b);return Ub(c,a)}
function kc(a){if(a.Db||a.Eb||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.b=qb(e.read(a.url),!0),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||eb(F.F);return b}
function lc(a,b,c,d,f){function g(){this.za=!1;this.aa=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Va(a/this.chunkSize|0)[b]}};g.prototype.Ib=function(a){this.Va=a};g.prototype.Na=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var h=this;h.Ib(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.aa[a]){var E=h.aa;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var n=new XMLHttpRequest;n.open("GET",c,!1);b!==g&&n.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(n.responseType="arraybuffer");
n.overrideMimeType&&n.overrideMimeType("text/plain; charset=x-user-defined");n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);d=void 0!==n.response?new Uint8Array(n.response||[]):qb(n.responseText||"",!0);E[a]=d}if("undefined"===typeof h.aa[a])throw Error("doXHR failed!");return h.aa[a]});if(a||!b)g=b=1,g=b=this.Va(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.qb=b;this.pb=
g;this.za=!0};if("undefined"!==typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.za||this.Na();return this.qb}},chunkSize:{get:function(){this.za||this.Na();return this.pb}}});var n=void 0}else n=c,h=void 0;var p=hc(a,b,d,f);h?p.b=h:n&&(p.b=null,p.url=n);Object.defineProperties(p,{g:{get:function(){return this.b.length}}});var r={};
Object.keys(p.f).forEach(function(a){var b=p.f[a];r[a]=function(){if(!kc(p))throw new H(F.F);return b.apply(null,arguments)}});r.read=function(a,b,c,d,f){if(!kc(p))throw new H(F.F);a=a.node.b;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};p.f=r;return p}
function mc(a,b,c,d,f,g,h,n,p,r){function u(c){function E(c){r&&r();n||ic(a,b,c,d,f,p);g&&g();Za()}var V=!1;e.preloadPlugins.forEach(function(a){!V&&a.canHandle(B)&&(a.handle(c,B,E,function(){h&&h();Za()}),V=!0)});V||E(c)}nc();var B=b?lb(G(a,b)):a;Ya();"string"==typeof c?oc(c,function(a){u(a)},h):u(c)}var FS={},Jb,Pb,Yb,pc={},P=0;function Q(){P+=4;return x[P-4>>2]}function qc(){var a=L[Q()];if(!a)throw new H(F.Y);return a}
var rc=null,sc="",tc=0,uc=null,vc=0,wc=0,xc=0,yc=0,zc=[],Ac={},Bc,Cc,Dc,Ec=!1,Fc=!1,Gc=[];
function nc(){function a(){Fc=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!Hc){Hc=!0;try{Ic=!0}catch(c){Ic=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Jc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Ic?null:console.log("warning: no BlobBuilder");
Kc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.ab||"undefined"!==typeof Kc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.ab=!0);e.preloadPlugins.push({canHandle:function(a){return!e.ab&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(Ic)try{c=new Blob([a],{type:Lc(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:Lc(b)}))}catch(r){la("Blob constructor present but fails: "+
r+"; falling back to blob builder")}c||(c=new Jc,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=Kc.createObjectURL(c),p=new Image;p.onload=function(){assert(p.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=p.width;c.height=p.height;c.getContext("2d").drawImage(p,0,0);e.preloadedImages[b]=c;Kc.revokeObjectURL(d);f&&f(a)};p.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};p.src=d}});e.preloadPlugins.push({canHandle:function(a){return!e.de&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){p||(p=!0,e.preloadedAudios[b]=c,f&&f(a))}function d(){p||(p=!0,e.preloadedAudios[b]=new Audio,g&&g())}var p=!1;if(Ic){try{var r=new Blob([a],{type:Lc(b)})}catch(B){return d()}r=Kc.createObjectURL(r);var u=new Audio;u.addEventListener("canplaythrough",function(){c(u)},!1);u.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,g=0,
h=0;h<a.length;h++)for(f=f<<8|a[h],g+=8;6<=g;){var n=f>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[n]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");u.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(u)}};u.src=r;Mc(function(){c(u)})}else return d()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(a){!Fc&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function Nc(a,b,c,d){if(b&&e.I&&a==e.canvas)return e.I;if(b){var f={antialias:!1,alpha:!1};if(d)for(var g in d)f[g]=d[g];if(f=Oc(a,f))var h=Pc[f].GLctx}else h=a.getContext("2d");if(!h)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.I=h,b&&Qc(f),e.ge=b,Gc.forEach(function(a){a()}),nc());return h}var Rc=!1,Sc=void 0,Tc=void 0;
function Uc(a,b,c){function d(){Ec=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),Sc&&f.requestPointerLock(),Ec=!0,Tc&&("undefined"!=typeof SDL&&
(x[SDL.screen>>2]=Ea[SDL.screen>>2]|8388608),Vc())):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),Tc&&("undefined"!=typeof SDL&&(x[SDL.screen>>2]=Ea[SDL.screen>>2]&-8388609),Vc()));if(e.onFullScreen)e.onFullScreen(Ec);if(e.onFullscreen)e.onFullscreen(Ec);Wc(f)}Sc=a;Tc=b;Xc=c;"undefined"===typeof Sc&&(Sc=!0);"undefined"===typeof Tc&&(Tc=!1);"undefined"===typeof Xc&&(Xc=null);var f=e.canvas;Rc||(Rc=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",
d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({he:c}):
g.requestFullscreen()}function Yc(a,b,c){e.printErr("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");Yc=function(a,b,c){return Uc(a,b,c)};return Uc(a,b,c)}var Zc=0;function $c(a){var b=Date.now();if(0===Zc)Zc=b+1E3/60;else for(;b+2>=Zc;)Zc+=1E3/60;setTimeout(a,Math.max(Zc-b,0))}
function ad(a){"undefined"===typeof window?$c(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||$c),window.requestAnimationFrame(a))}function Mc(a){e.noExitRuntime=!0;setTimeout(function(){na||a()},1E4)}
function Lc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var bd=0,cd=0,dd=0,ed=0;
function fd(a){if(Fc)"mousemove"!=a.type&&"mozMovementX"in a?dd=ed=0:(dd=a.movementX||a.mozMovementX||a.webkitMovementX||0,ed=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(bd=SDL.be+dd,cd=SDL.ce+ed):(bd+=dd,cd+=ed);else{var b=e.canvas.getBoundingClientRect(),c=e.canvas.width,d=e.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(f=a.pageX-(f+b.left),a=a.pageY-(g+b.top),f*=c/b.width,a*=d/b.height,dd=f-bd,ed=a-cd,bd=f,cd=a)}}function oc(a,b,c){var d="al "+a;e.readAsync(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));d&&Za()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ya()}var gd=[];function Vc(){var a=e.canvas;gd.forEach(function(b){b(a.width,a.height)})}function hd(a,b,c){Wc(e.canvas,a,b);c||Vc()}
function Wc(a,b,c){b&&c?(a.Qb=b,a.Ab=c):(b=a.Qb,c=a.Ab);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}Tc?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Hc,Ic,Jc,Kc,Xc;
function id(a,b){wc=a;xc=b;if(uc)if(0==a)rc=function(){var a=Math.max(0,Cc+b-R())|0;setTimeout(Dc,a)},sc="timeout";else if(1==a)rc=function(){ad(Dc)},sc="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);l?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(a),postMessage({target:"setimmediate"})):
postMessage("setimmediate","*")}}rc=function(){setImmediate(Dc)};sc="immediate"}}function R(){t()}
function jd(a,b,c,d,f){e.noExitRuntime=!0;assert(!uc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");uc=a;vc=d;var g="undefined"!==typeof d?function(){e.dynCall_vi(a,d)}:function(){e.dynCall_v(a)};var h=tc;Dc=function(){if(!na)if(0<zc.length){var a=Date.now(),b=zc.shift();b.ea(b.$);if(Bc){var c=Bc,d=0==c%1?c-1:Math.floor(c);Bc=b.Ud?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");e.setStatus&&(a=e.statusMessage||"Please wait...",b=Bc,c=Ac.Wd,b?b<c?e.setStatus(a+" ("+(c-b)+"/"+c+")"):e.setStatus(a):e.setStatus(""));h<tc||setTimeout(Dc,0)}else if(!(h<tc))if(yc=yc+1|0,1==wc&&1<xc&&0!=yc%xc)rc();else{0==wc&&(Cc=R());if(S)for(a=S.P,S.P=S.X,S.X=a,a=S.C,S.C=S.ia,S.ia=a,a=kd[2097152],b=0;b<=a;++b)S.C[b]=0;"timeout"===sc&&e.I&&(e.printErr("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
sc="");a:if(!(na||e.preMainLoop&&!1===e.preMainLoop())){try{g()}catch(B){if(B instanceof fa)break a;B&&"object"===typeof B&&B.stack&&e.printErr("exception thrown: "+[B,B.stack]);throw B;}e.postMainLoop&&e.postMainLoop()}h<tc||("object"===typeof SDL&&SDL.audio&&SDL.audio.Gb&&SDL.audio.Gb(),rc())}};f||(b&&0<b?id(0,1E3/b):id(1,1),rc());if(c)throw"SimulateInfiniteLoop";}var ld=q;q+=16;var md,T={};
function nd(a){if(0===a)return 0;a=A(a);if(!T.hasOwnProperty(a))return 0;nd.j&&od(nd.j);a=T[a];var b=Aa(a)+1,c=wa(b);c&&za(a,w,c,b);nd.j=c;return nd.j}var pd=1,qd=0,rd=[],U=[],sd=[],td=[],W=[],Pc=[],S=null,ud=0,vd=0,wd=[1,1,2,2,4,4,4,2,3,4,8],xd={},yd=[],zd=4;function X(a){qd||(qd=a)}function Ad(a){for(var b=pd++,c=a.length;c<b;c++)a[c]=null;return b}var Bd=null,Cd=[0],kd=null;
function Dd(a){var b=kd[2097152];a.C=[];a.ia=[];a.C.length=a.ia.length=b+1;a.P=[];a.X=[];a.P.length=a.X.length=b+1;a.O=[];a.O.length=b+1;for(var c=0;c<=b;++c){a.O[c]=null;a.C[c]=a.ia[c]=0;a.P[c]=[];a.X[c]=[];var d=a.P[c],f=a.X[c];d.length=f.length=64;for(var g=0;64>g;++g)d[g]=f[g]=null}}
function Oc(a,b){function c(a){d=a.statusMessage||d}"undefined"===typeof b.majorVersion&&"undefined"===typeof b.minorVersion&&(b.majorVersion=1,b.minorVersion=0);var d="?";try{a.addEventListener("webglcontextcreationerror",c,!1);try{if(1==b.majorVersion&&0==b.minorVersion)var f=a.getContext("webgl",b)||a.getContext("experimental-webgl",b);else if(2==b.majorVersion&&0==b.minorVersion)f=a.getContext("webgl2",b);else throw"Unsupported WebGL context version "+majorVersion+"."+minorVersion+"!";}finally{a.removeEventListener("webglcontextcreationerror",
c,!1)}if(!f)throw":(";}catch(g){return e.print("Could not create canvas: "+[d,g,JSON.stringify(b)]),0}return f?Ed(f,b):0}function Ed(a,b){var c=Ad(Pc),d={handle:c,attributes:b,version:b.majorVersion,GLctx:a};a.canvas&&(a.canvas.Rd=d);Pc[c]=d;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&Fd(d);return c}function Qc(a){if(a=Pc[a])GLctx=e.I=a.GLctx,S=a}
function Fd(a){a||(a=S);if(!a.Bb){a.Bb=!0;var b=a.GLctx;a.Ya=b.getParameter(b.MAX_VERTEX_ATTRIBS);a.ba=[];for(var c=0;c<a.Ya;c++)a.ba[c]={enabled:!1,pa:!1,size:0,type:0,bb:0,Fa:0,ha:0};Dd(a);if(2>a.version){var d=b.getExtension("ANGLE_instanced_arrays");d&&(b.vertexAttribDivisor=function(a,b){d.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,c,f){d.drawArraysInstancedANGLE(a,b,c,f)},b.drawElementsInstanced=function(a,b,c,f,g){d.drawElementsInstancedANGLE(a,b,c,f,g)});var f=b.getExtension("OES_vertex_array_object");
f&&(b.createVertexArray=function(){return f.createVertexArrayOES()},b.deleteVertexArray=function(a){f.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){f.bindVertexArrayOES(a)},b.isVertexArray=function(a){return f.isVertexArrayOES(a)});var g=b.getExtension("WEBGL_draw_buffers");g&&(b.drawBuffers=function(a,b){g.drawBuffersWEBGL(a,b)})}b.Vd=b.getExtension("EXT_disjoint_timer_query");var h="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear WEBGL_compressed_texture_atc WEBKIT_WEBGL_compressed_texture_pvrtc WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_frag_depth EXT_sRGB WEBGL_draw_buffers WEBGL_shared_resources EXT_shader_texture_lod EXT_color_buffer_float".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=h.indexOf(a)&&b.getExtension(a)})}}var Gd;
function _glDrawElements(a,b,c,d){if(!vd){var f=1*wd[c-5120]*b;var g=kd[f];var h=S.O[g];h?g=h:(h=GLctx.getParameter(GLctx.ELEMENT_ARRAY_BUFFER_BINDING),S.O[g]=GLctx.createBuffer(),GLctx.bindBuffer(GLctx.ELEMENT_ARRAY_BUFFER,S.O[g]),GLctx.bufferData(GLctx.ELEMENT_ARRAY_BUFFER,1<<g,GLctx.DYNAMIC_DRAW),GLctx.bindBuffer(GLctx.ELEMENT_ARRAY_BUFFER,h),g=S.O[g]);GLctx.bindBuffer(GLctx.ELEMENT_ARRAY_BUFFER,g);GLctx.bufferSubData(GLctx.ELEMENT_ARRAY_BUFFER,0,z.subarray(d,d+f));d=0}Gd=!1;for(f=0;f<S.Ya;++f)if(g=
S.ba[f],g.pa&&g.enabled){Gd=!0;h=g.Fa;h=0<h?b*h:g.size*wd[g.type-5120]*b;var n=kd[h];var p=S.P[n],r=S.C[n];S.C[n]=S.C[n]+1&63;var u=p[r];u?n=u:(u=GLctx.getParameter(GLctx.ARRAY_BUFFER_BINDING),p[r]=GLctx.createBuffer(),GLctx.bindBuffer(GLctx.ARRAY_BUFFER,p[r]),GLctx.bufferData(GLctx.ARRAY_BUFFER,1<<n,GLctx.DYNAMIC_DRAW),GLctx.bindBuffer(GLctx.ARRAY_BUFFER,u),n=p[r]);GLctx.bindBuffer(GLctx.ARRAY_BUFFER,n);GLctx.bufferSubData(GLctx.ARRAY_BUFFER,0,z.subarray(g.ha,g.ha+h));GLctx.vertexAttribPointer(f,
g.size,g.type,g.bb,g.Fa,0)}GLctx.drawElements(a,b,c,d);Gd&&GLctx.bindBuffer(GLctx.ARRAY_BUFFER,rd[ud]);vd||GLctx.bindBuffer(GLctx.ELEMENT_ARRAY_BUFFER,null)}
function Hd(a,b,c,d,f){switch(b){case 6406:case 6409:case 6402:b=1;break;case 6410:b=2;break;case 6407:case 35904:b=3;break;case 6408:case 35906:b=4;break;default:return X(1280),null}switch(a){case 5121:var g=1*b;break;case 5123:case 36193:g=2*b;break;case 5125:case 5126:g=4*b;break;case 34042:g=4;break;case 33635:case 32819:case 32820:g=2;break;default:return X(1280),null}b=zd;c*=g;b*=Math.floor((c+b-1)/b);d=0>=d?0:(d-1)*b+c;switch(a){case 5121:return z.subarray(f,f+d);case 5126:return y.subarray(f>>
2,f+d>>2);case 5125:case 34042:return Ea.subarray(f>>2,f+d>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return Da.subarray(f>>1,f+d>>1);default:return X(1280),null}}function Id(a,b,c,d){this.id=a;this.y=this.x=0;this.wa=!1;this.ib=this.hb=0;this.width=b;this.height=c;this.gb=b;this.fb=c;this.title=d;this.attributes=Jd;this.buttons=0;this.keys=[];this.ra=[];this.Oa=this.Wa=this.sa=this.eb=this.da=this.qa=this.Ba=this.va=this.lb=this.mb=this.title=null}
function Kd(a){return 0>=a||!Y?null:Y[a-1]}var Z=null,Y=null,Ld=null,Jd=null,Md={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Nd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Od(){var a=Z,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Pd(a){Z&&Z.Oa&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||e.dynCall_vii(Z.Oa,Z.id,a))}
function Qd(a,b){if(Z){var c=Nd(a);if(-1!=c){var d=b&&Z.keys[c];Z.keys[c]=b;Z.ra[a]=b;Z.Wa&&(d&&(b=2),e.dynCall_viiiii(Z.Wa,Z.id,c,a,b,Od()))}}}function Rd(){Sd()}function Td(){Sd()}function Ud(a){Qd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Vd(a){Qd(a.keyCode,0)}function Wd(){if(Z)for(var a=0;a<Z.ra.length;++a)Z.ra[a]&&Qd(a,0)}function Xd(a){Z&&(fd(a),a.target==e.canvas&&Z.qa&&e.dynCall_vidd(Z.qa,Z.id,bd,cd))}
function Yd(a){Z&&a.target==e.canvas&&Z.da&&e.dynCall_vii(Z.da,Z.id,1)}function Zd(a){Z&&a.target==e.canvas&&Z.da&&e.dynCall_vii(Z.da,Z.id,0)}function $d(a,b){if(Z&&(fd(a),a.target==e.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Z.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Z.buttons&=~(1<<c);Z.Ba&&e.dynCall_viiii(Z.Ba,Z.id,c,b,Od())}}function ae(a){Z&&$d(a,1)}function be(a){Z&&$d(a,0)}
function ce(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Z&&Z.eb&&a.target==e.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;e.dynCall_vidd(Z.eb,Z.id,b,c);a.preventDefault()}}function de(){(e.canvas.requestFullscreen||e.canvas.mozRequestFullScreen||e.canvas.webkitRequestFullScreen||function(){}).apply(e.canvas,[])}var ee={},fe=null,ge=null;
function Sd(){if(yc!==ge||!yc){fe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;ge=yc;for(var a=0;a<fe.length;++a){var b=fe[a];if(b){ee[a]||(console.log("glfw joystick connected:",a),ee[a]={id:va(qb(b.id),"i8"),Td:b.buttons.length,Sd:b.axes.length,buttons:va(Array(b.buttons.length),"i8"),axes:va(Array(4*b.axes.length),"float")});for(var c=ee[a],d=0;d<b.buttons.length;++d)v(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)v(c.axes+
4*d,b.axes[d],"float")}else ee[a]&&(console.log("glfw joystick disconnected",a),od(ee[a].id),od(ee[a].buttons),od(ee[a].axes),delete ee[a])}}}
function he(a){function b(a){var b="/.glfw_dropped_files/"+a.name.replace(/\//g,"_"),n=new FileReader;n.onloadend=function(h){if(2!=n.readyState)++g,console.log("failed to read dropped file: "+a.name+": "+n.error);else{var p=new Uint8Array(h.target.result);h={};h.flags=h.flags||"w";var E=Xb(b,h.flags,h.mode);if("string"===typeof p){var r=new Uint8Array(Aa(p)+1);p=za(p,r,0,r.length);ac(E,r,0,p,void 0,h.vb)}else if(ArrayBuffer.isView(p))ac(E,p,0,p.byteLength,void 0,h.vb);else throw Error("Unsupported data type");
Zb(E);if(++g===f){e.dynCall_viii(Z.sa,Z.id,f,c);for(h=0;h<d.length;++h)od(d[h]);od(c)}}};n.readAsArrayBuffer(a);var u=va(qb(b),"i8");d.push(u);v(c+4*h,u,"i8*")}if(Z&&Z.sa&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=va(Array(4*a.dataTransfer.files.length),"i8*"),d=[],f=a.dataTransfer.files.length,g=0;fc("/",".glfw_dropped_files");for(var h=0;h<f;++h)b(a.dataTransfer.files[h]);return!1}}function ie(a){if(Z&&Z.sa)return a.preventDefault(),!1}
var je={},ke=1;function le(a,b){le.j||(le.j={});a in le.j||(e.dynCall_v(b),le.j[a]=1)}function me(a){return 0===a%4&&(0!==a%100||0===a%400)}function ne(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var oe=[31,29,31,30,31,30,31,31,30,31,30,31],pe=[31,28,31,30,31,30,31,31,30,31,30,31];
function qe(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(me(a.getFullYear())?oe:pe)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function re(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function p(a){a=qe(new Date(a.i+1900,0,1),a.ka);var b=n(new Date(a.getFullYear()+1,0,4));return 0>=h(n(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var r=x[d+40>>2];d={Nb:x[d>>2],Mb:x[d+4>>2],ja:x[d+8>>2],J:x[d+12>>2],D:x[d+16>>2],i:x[d+20>>2],jb:x[d+24>>2],ka:x[d+28>>2],fe:x[d+32>>2],Lb:x[d+36>>2],Ob:r?
A(r):""};c=A(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var u in r)c=c.replace(new RegExp(u,"g"),r[u]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),qa="January February March April May June July August September October November December".split(" ");r={"%a":function(a){return B[a.jb].substring(0,3)},"%A":function(a){return B[a.jb]},"%b":function(a){return qa[a.D].substring(0,
3)},"%B":function(a){return qa[a.D]},"%C":function(a){return g((a.i+1900)/100|0,2)},"%d":function(a){return g(a.J,2)},"%e":function(a){return f(a.J,2," ")},"%g":function(a){return p(a).toString().substring(2)},"%G":function(a){return p(a)},"%H":function(a){return g(a.ja,2)},"%I":function(a){a=a.ja;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.J+ne(me(a.i+1900)?oe:pe,a.D-1),3)},"%m":function(a){return g(a.D+1,2)},"%M":function(a){return g(a.Mb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=
a.ja&&12>a.ja?"AM":"PM"},"%S":function(a){return g(a.Nb,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.i+1900,a.D+1,a.J,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.i+1900,0,1),c=0===b.getDay()?b:qe(b,7-b.getDay());a=new Date(a.i+1900,a.D,a.J);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(ne(me(a.getFullYear())?oe:pe,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.i+1900,0,4)),c=n(new Date(a.i+1901,0,4)),d=qe(new Date(a.i+
1900,0,1),a.ka);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.i+1900?a.ka+32-b.getDate():a.ka+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.i+1900,a.D+1,a.J,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.i,0,1),c=1===b.getDay()?b:qe(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.i+1900,a.D,a.J);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(ne(me(a.getFullYear())?oe:pe,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.i+1900).toString().substring(2)},
"%Y":function(a){return a.i+1900},"%z":function(a){a=a.Lb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Ob},"%%":function(){return"%"}};for(u in r)0<=c.indexOf(u)&&(c=c.replace(new RegExp(u,"g"),r[u](d)));u=qb(c,!1);if(u.length>b)return 0;w.set(u,a);return u.length-1}bc();Bb=Array(4096);Rb(I,"/");N("/tmp");N("/home");N("/home/web_user");
(function(){N("/dev");ob(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Tb("/dev/null",259);nb(1280,rb);nb(1536,sb);Tb("/dev/tty",1280);Tb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else b=m?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};O("/dev","random",b);O("/dev","urandom",b);N("/dev/shm");N("/dev/shm/tmp")})();N("/proc");N("/proc/self");N("/proc/self/fd");
Rb({m:function(){var a=ub("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=L[+c];if(!b)throw new H(F.Y);a={parent:null,m:{$a:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Pa.unshift(function(){if(!e.noFSInit&&!cc){assert(!cc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");cc=!0;bc();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?O("/dev","stdin",e.stdin):Ub("/dev/tty","/dev/stdin");e.stdout?O("/dev","stdout",null,e.stdout):Ub("/dev/tty","/dev/stdout");e.stderr?O("/dev","stderr",null,e.stderr):Ub("/dev/tty1","/dev/stderr");var a=
Xb("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=Xb("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=Xb("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Qa.push(function(){Cb=!1});Ra.push(function(){cc=!1;var a=e._fflush;a&&a(0);for(a=0;a<L.length;a++){var b=L[a];b&&Zb(b)}});e.FS_createFolder=ec;e.FS_createPath=fc;e.FS_createDataFile=ic;e.FS_createPreloadedFile=mc;e.FS_createLazyFile=lc;e.FS_createLink=jc;
e.FS_createDevice=O;e.FS_unlink=Vb;Pa.unshift(function(){});Ra.push(function(){});if(m){var fs=require("fs"),xb=require("path");K.Kb()}e.requestFullScreen=function(a,b,c){e.printErr("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");e.requestFullScreen=e.requestFullscreen;Yc(a,b,c)};e.requestFullscreen=function(a,b,c){Uc(a,b,c)};e.requestAnimationFrame=function(a){ad(a)};e.setCanvasSize=function(a,b,c){hd(a,b,c)};e.pauseMainLoop=function(){rc=null;tc++};
e.resumeMainLoop=function(){tc++;var a=wc,b=xc,c=uc;uc=null;jd(c,0,!1,vc,!0);id(a,b);rc()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return Nc(a,b,c,d)};
m?R=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?R=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?R=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?R=function(){return performance.now()}:R=Date.now;var se,te;
md?(te=x[ld>>2],se=x[te>>2]):(md=!0,T.USER=T.LOGNAME="web_user",T.PATH="/",T.PWD="/",T.HOME="/home/web_user",T.LANG="C.UTF-8",T._=e.thisProgram,se=ha(1024),te=ha(256),x[te>>2]=se,x[ld>>2]=te);var ue=[],ve=0,we;for(we in T)if("string"===typeof T[we]){var xe=we+"="+T[we];ue.push(xe);ve+=xe.length}if(1024<ve)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");
for(var ye=0;ye<ue.length;ye++){for(var ze=xe=ue[ye],Ae=se,Be=0;Be<ze.length;++Be)w[Ae++>>0]=ze.charCodeAt(Be);w[Ae>>0]=0;x[te+4*ye>>2]=se;se+=xe.length+1}x[te+4*ue.length>>2]=0;var GLctx;kd=new Uint8Array(2097153);var Ce=0,De=1;kd[0]=0;for(var Ee=1;2097152>=Ee;++Ee)Ee>De&&(De<<=1,++Ce),kd[Ee]=Ce;Bd=new Float32Array(256);for(var Fe=0;256>Fe;Fe++)Cd[Fe]=Bd.subarray(0,Fe+1);for(Fe=0;32>Fe;Fe++)yd.push(Array(Fe));C=ha(4);Ha=Ia=ja(q);Ja=Ha+Ma;Ka=ja(Ja);x[C>>2]=Ka;ia=!0;
function qb(a,b){var c=Array(Aa(a)+1);a=za(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=704;e.wasmMaxTableSize=704;e.sb={};
e.tb={abort:t,enlargeMemory:function(){La()},getTotalMemory:function(){return D},abortOnCannotGrowMemory:La,__ZSt18uncaught_exceptionv:db,___cxa_allocate_exception:function(a){return wa(a)},___cxa_throw:function(a){"uncaught_exception"in db?db.j++:db.j=1;throw a+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},___lock:function(){},___map_file:function(){eb(F.G);return-1},___setErrNo:eb,___syscall140:function(a,
b){P=b;try{var c=qc();Q();var d=Q(),f=Q(),g=Q();$b(c,d,g);x[f>>2]=c.position;c.ya&&0===d&&0===g&&(c.ya=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof H||t(h),-h.u}},___syscall145:function(a,b){P=b;try{var c=qc(),d=Q();a:{var f=Q();for(b=a=0;b<f;b++){var g=x[d+(8*b+4)>>2],h=c,n=x[d+8*b>>2],p=g,r=void 0,u=w;if(0>p||0>r)throw new H(F.h);if(1===(h.flags&2097155))throw new H(F.Y);if(J(h.node.mode))throw new H(F.R);if(!h.f.read)throw new H(F.h);var B="undefined"!==typeof r;if(!B)r=
h.position;else if(!h.seekable)throw new H(F.Z);var qa=h.f.read(h,u,n,p,r);B||(h.position+=qa);var E=qa;if(0>E){var V=-1;break a}a+=E;if(E<g)break}V=a}return V}catch(Qb){return"undefined"!==typeof FS&&Qb instanceof H||t(Qb),-Qb.u}},___syscall146:function(a,b){P=b;try{var c=qc(),d=Q();a:{var f=Q();for(b=a=0;b<f;b++){var g=ac(c,w,x[d+8*b>>2],x[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(n){return"undefined"!==typeof FS&&n instanceof H||t(n),-n.u}},___syscall221:function(a,
b){P=b;try{var c=qc();switch(Q()){case 0:var d=Q();return 0>d?-F.h:Xb(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Q(),c.flags|=d,0;case 12:case 12:return d=Q(),oa[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-F.h;case 9:return eb(F.h),-1;default:return-F.h}}catch(f){return"undefined"!==typeof FS&&f instanceof H||t(f),-f.u}},___syscall5:function(a,b){P=b;try{var c=A(Q()),d=Q(),f=Q();return Xb(c,d,f).fd}catch(g){return"undefined"!==
typeof FS&&g instanceof H||t(g),-g.u}},___syscall54:function(a,b){P=b;try{var c=qc(),d=Q();switch(d){case 21509:case 21505:return c.tty?0:-F.K;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-F.K;case 21519:if(!c.tty)return-F.K;var f=Q();return x[f>>2]=0;case 21520:return c.tty?-F.h:-F.K;case 21531:a=f=Q();if(!c.f.Cb)throw new H(F.K);return c.f.Cb(c,d,a);case 21523:return c.tty?0:-F.K;default:t("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof FS&&g instanceof
H||t(g),-g.u}},___syscall6:function(a,b){P=b;try{var c=qc();Zb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof H||t(d),-d.u}},___syscall91:function(a,b){P=b;try{var c=Q(),d=Q(),f=pc[c];if(!f)return 0;if(d===f.$d){var g=L[f.fd],h=f.flags,n=new Uint8Array(z.subarray(c,c+d));g&&g.f.ga&&g.f.ga(g,n,0,d,h);pc[c]=null;f.rb&&od(f.ae)}return 0}catch(p){return"undefined"!==typeof FS&&p instanceof H||t(p),-p.u}},___unlock:function(){},_abort:function(){e.abort()},_emscripten_memcpy_big:function(a,
b,c){z.set(z.subarray(b,b+c),a);return a},_emscripten_set_main_loop:jd,_exit:function(a){e.exit(a)},_getenv:nd,_glActiveTexture:function(a){GLctx.activeTexture(a)},_glAttachShader:function(a,b){GLctx.attachShader(U[a],W[b])},_glBindBuffer:function(a,b){var c=b?rd[b]:null;a==GLctx.ARRAY_BUFFER?ud=b:a==GLctx.ELEMENT_ARRAY_BUFFER&&(vd=b);GLctx.bindBuffer(a,c)},_glBindTexture:function(a,b){GLctx.bindTexture(a,b?sd[b]:null)},_glBlendFunc:function(a,b){GLctx.blendFunc(a,b)},_glBufferData:function(a,b,c,
d){c?GLctx.bufferData(a,z.subarray(c,c+b),d):GLctx.bufferData(a,b,d)},_glClear:function(a){GLctx.clear(a)},_glClearColor:function(a,b,c,d){GLctx.clearColor(a,b,c,d)},_glCompileShader:function(a){GLctx.compileShader(W[a])},_glCompressedTexImage2D:function(a,b,c,d,f,g,h,n){GLctx.compressedTexImage2D(a,b,c,d,f,g,n?z.subarray(n,n+h):null)},_glCreateProgram:function(){var a=Ad(U),b=GLctx.createProgram();b.name=a;U[a]=b;return a},_glCreateShader:function(a){var b=Ad(W);W[b]=GLctx.createShader(a);return b},
_glCullFace:function(a){GLctx.cullFace(a)},_glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],f=rd[d];f&&(GLctx.deleteBuffer(f),f.name=0,rd[d]=null,d==ud&&(ud=0),d==vd&&(vd=0))}},_glDeleteProgram:function(a){if(a){var b=U[a];b?(GLctx.deleteProgram(b),b.name=0,U[a]=null,xd[a]=null):X(1281)}},_glDeleteShader:function(a){if(a){var b=W[a];b?(GLctx.deleteShader(b),W[a]=null):X(1281)}},_glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],f=sd[d];f&&(GLctx.deleteTexture(f),
f.name=0,sd[d]=null)}},_glDepthFunc:function(a){GLctx.depthFunc(a)},_glDisable:function(a){GLctx.disable(a)},_glDrawElements:_glDrawElements,_glEnable:function(a){GLctx.enable(a)},_glEnableVertexAttribArray:function(a){S.ba[a].enabled=!0;GLctx.enableVertexAttribArray(a)},_glFrontFace:function(a){GLctx.frontFace(a)},_glGenBuffers:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createBuffer();if(!d){for(X(1282);c<a;)x[b+4*c++>>2]=0;break}var f=Ad(rd);d.name=f;rd[f]=d;x[b+4*c>>2]=f}},_glGenTextures:function(a,
b){for(var c=0;c<a;c++){var d=GLctx.createTexture();if(!d){for(X(1282);c<a;)x[b+4*c++>>2]=0;break}var f=Ad(sd);d.name=f;sd[f]=d;x[b+4*c>>2]=f}},_glGetAttribLocation:function(a,b){a=U[a];b=A(b);return GLctx.getAttribLocation(a,b)},_glGetProgramInfoLog:function(a,b,c,d){a=GLctx.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");0<b&&d?(b=za(a,z,d,b),c&&(x[c>>2]=b)):c&&(x[c>>2]=0)},_glGetProgramiv:function(a,b,c){if(c)if(a>=pd)X(1281);else{var d=xd[a];if(d)if(35716==b)a=GLctx.getProgramInfoLog(U[a]),
null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.Aa;else if(35722==b){if(-1==d.S){a=U[a];var f=GLctx.getProgramParameter(a,GLctx.ACTIVE_ATTRIBUTES);for(b=d.S=0;b<f;++b)d.S=Math.max(d.S,GLctx.getActiveAttrib(a,b).name.length+1)}x[c>>2]=d.S}else if(35381==b){if(-1==d.T)for(a=U[a],f=GLctx.getProgramParameter(a,GLctx.Rb),b=d.T=0;b<f;++b){var g=GLctx.Yd(a,b);d.T=Math.max(d.T,g.length+1)}x[c>>2]=d.T}else x[c>>2]=GLctx.getProgramParameter(U[a],b);else X(1282)}else X(1281)},_glGetShaderInfoLog:function(a,
b,c,d){a=GLctx.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");0<b&&d?(b=za(a,z,d,b),c&&(x[c>>2]=b)):c&&(x[c>>2]=0)},_glGetShaderiv:function(a,b,c){c?35716==b?(a=GLctx.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1):35720==b?(a=GLctx.getShaderSource(W[a]),x[c>>2]=null===a||0==a.length?0:a.length+1):x[c>>2]=GLctx.getShaderParameter(W[a],b):X(1281)},_glGetUniformLocation:function(a,b){b=A(b);var c=0;if(-1!==b.indexOf("]",b.length-1)){var d=b.lastIndexOf("["),f=b.slice(d+
1,-1);if(0<f.length&&(c=parseInt(f),0>c))return-1;b=b.slice(0,d)}a=xd[a];return a?(b=a.kb[b])&&c<b[0]?b[1]+c:-1:-1},_glIsBuffer:function(a){return(a=rd[a])?GLctx.isBuffer(a):0},_glIsTexture:function(a){return(a=sd[a])?GLctx.isTexture(a):0},_glLinkProgram:function(a){GLctx.linkProgram(U[a]);xd[a]=null;var b=U[a];xd[a]={kb:{},Aa:0,S:-1,T:-1};a=xd[a];for(var c=a.kb,d=GLctx.getProgramParameter(b,GLctx.ACTIVE_UNIFORMS),f=0;f<d;++f){var g=GLctx.getActiveUniform(b,f),h=g.name;a.Aa=Math.max(a.Aa,h.length+
1);-1!==h.indexOf("]",h.length-1)&&(h=h.slice(0,h.lastIndexOf("[")));var n=GLctx.getUniformLocation(b,h);if(null!=n){var p=Ad(td);c[h]=[g.size,p];td[p]=n;for(var r=1;r<g.size;++r)n=GLctx.getUniformLocation(b,h+"["+r+"]"),p=Ad(td),td[p]=n}}},_glPixelStorei:function(a,b){3333==a||3317==a&&(zd=b);GLctx.pixelStorei(a,b)},_glShaderSource:function(a,b,c,d){for(var f="",g=0;g<b;++g){if(d){var h=x[d+4*g>>2];h=0>h?A(x[c+4*g>>2]):A(x[c+4*g>>2],h)}else h=A(x[c+4*g>>2]);f+=h}GLctx.shaderSource(W[a],f)},_glTexImage2D:function(a,
b,c,d,f,g,h,n,p){var r=null;p&&(r=Hd(n,h,d,f,p));GLctx.texImage2D(a,b,c,d,f,g,h,n,r)},_glTexParameteri:function(a,b,c){GLctx.texParameteri(a,b,c)},_glUniform4f:function(a,b,c,d,f){GLctx.uniform4f(td[a],b,c,d,f)},_glUniformMatrix4fv:function(a,b,c,d){if(256>=16*b){var f=Cd[16*b-1];for(var g=0;g<16*b;g+=16)f[g]=y[d+4*g>>2],f[g+1]=y[d+(4*g+4)>>2],f[g+2]=y[d+(4*g+8)>>2],f[g+3]=y[d+(4*g+12)>>2],f[g+4]=y[d+(4*g+16)>>2],f[g+5]=y[d+(4*g+20)>>2],f[g+6]=y[d+(4*g+24)>>2],f[g+7]=y[d+(4*g+28)>>2],f[g+8]=y[d+(4*
g+32)>>2],f[g+9]=y[d+(4*g+36)>>2],f[g+10]=y[d+(4*g+40)>>2],f[g+11]=y[d+(4*g+44)>>2],f[g+12]=y[d+(4*g+48)>>2],f[g+13]=y[d+(4*g+52)>>2],f[g+14]=y[d+(4*g+56)>>2],f[g+15]=y[d+(4*g+60)>>2]}else f=y.subarray(d>>2,d+64*b>>2);GLctx.uniformMatrix4fv(td[a],!!c,f)},_glUseProgram:function(a){GLctx.useProgram(a?U[a]:null)},_glVertexAttribPointer:function(a,b,c,d,f,g){var h=S.ba[a];ud?(h.pa=!1,GLctx.vertexAttribPointer(a,b,c,!!d,f,g)):(h.size=b,h.type=c,h.bb=d,h.Fa=f,h.ha=g,h.pa=!0)},_glViewport:function(a,b,c,
d){GLctx.viewport(a,b,c,d)},_glfwCreateWindow:function(a,b,c,d){var f;for(f=0;f<Y.length&&null!==Y[f];f++);if(0<f)throw"glfwCreateWindow only supports one window at time currently";var g=f+1;if(0>=a||0>=b)g=0;else{d?de():hd(a,b);for(f=0;f<Y.length&&null==Y[f];f++);f==Y.length&&(e.I=Nc(e.canvas,!0,!0,{antialias:1<Jd[135181],depth:0<Jd[135173],stencil:0<Jd[135174],alpha:0<Jd[135172]}));e.I?(a=new Id(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,Z=a,g=a.id):g=0}return g},_glfwDestroyWindow:function(a){a:{if(a=
Kd(a)){a.lb&&e.dynCall_vi(a.lb,a.id);Y[a.id-1]=null;Z.id==a.id&&(Z=null);for(a=0;a<Y.length;a++)if(null!==Y[a]){a=void 0;break a}e.I=void 0}a=void 0}return a},_glfwGetCursorPos:function(a,b,c){v(b,bd,"double");v(c,cd,"double")},_glfwGetTime:function(){return R()/1E3-Ld},_glfwGetVersion:function(a,b,c){v(a,3,"i32");v(b,2,"i32");v(c,1,"i32")},_glfwGetWindowSize:function(a,b,c){var d=0,f=0;if(a=Kd(a))d=a.width,f=a.height;v(b,d,"i32");v(c,f,"i32")},_glfwInit:function(){if(Y)return 1;Ld=R()/1E3;Jd=Md;
Y=[];Z=null;window.addEventListener("gamepadconnected",Rd,!0);window.addEventListener("gamepaddisconnected",Td,!0);window.addEventListener("keydown",Ud,!0);window.addEventListener("keypress",Pd,!0);window.addEventListener("keyup",Vd,!0);window.addEventListener("blur",Wd,!0);e.canvas.addEventListener("mousemove",Xd,!0);e.canvas.addEventListener("mousedown",ae,!0);e.canvas.addEventListener("mouseup",be,!0);e.canvas.addEventListener("wheel",ce,!0);e.canvas.addEventListener("mousewheel",ce,!0);e.canvas.addEventListener("mouseenter",
Yd,!0);e.canvas.addEventListener("mouseleave",Zd,!0);e.canvas.addEventListener("drop",he,!0);e.canvas.addEventListener("dragover",ie,!0);gd.push(function(a,b){if(Z){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Z.hb=Z.x,Z.ib=Z.y,Z.gb=Z.width,Z.fb=Z.height,Z.x=Z.y=0,Z.width=screen.width,Z.height=screen.height,Z.wa=!0):1==Z.wa?(Z.x=Z.hb,Z.y=Z.ib,Z.width=Z.gb,Z.height=Z.fb,Z.wa=!1):Z.width!=a||Z.height!=b?(Z.width=a,Z.height=b):c=!1;c&&(hd(Z.width,
Z.height,!0),Z&&Z.mb&&e.dynCall_viii(Z.mb,Z.id,Z.width,Z.height),Z&&Z.va&&e.dynCall_viii(Z.va,Z.id,Z.width,Z.height))}});return 1},_glfwMakeContextCurrent:function(){},_glfwPollEvents:function(){},_glfwSetCursorPosCallback:function(a,b){if(a=Kd(a))a.qa=b},_glfwSetFramebufferSizeCallback:function(a,b){if(a=Kd(a))a.va=b},_glfwSetMouseButtonCallback:function(a,b){if(a=Kd(a))a.Ba=b},_glfwSwapBuffers:function(){},_glfwTerminate:function(){window.removeEventListener("gamepadconnected",Rd,!0);window.removeEventListener("gamepaddisconnected",
Td,!0);window.removeEventListener("keydown",Ud,!0);window.removeEventListener("keypress",Pd,!0);window.removeEventListener("keyup",Vd,!0);window.removeEventListener("blur",Wd,!0);e.canvas.removeEventListener("mousemove",Xd,!0);e.canvas.removeEventListener("mousedown",ae,!0);e.canvas.removeEventListener("mouseup",be,!0);e.canvas.removeEventListener("wheel",ce,!0);e.canvas.removeEventListener("mousewheel",ce,!0);e.canvas.removeEventListener("mouseenter",Yd,!0);e.canvas.removeEventListener("mouseleave",
Zd,!0);e.canvas.removeEventListener("drop",he,!0);e.canvas.removeEventListener("dragover",ie,!0);e.canvas.width=e.canvas.height=1;Z=Y=null},_glfwWindowHint:function(a,b){Jd[a]=b},_pthread_cond_wait:function(){return 0},_pthread_getspecific:function(a){return je[a]||0},_pthread_key_create:function(a){if(0==a)return F.h;x[a>>2]=ke;je[ke]=0;ke++;return 0},_pthread_once:le,_pthread_setspecific:function(a,b){if(!(a in je))return F.h;je[a]=b;return 0},_strftime_l:function(a,b,c,d){return re(a,b,c,d)},DYNAMICTOP_PTR:C,
STACKTOP:Ia};var Ge=e.asm(e.sb,e.tb,buffer);e.asm=Ge;var ab=e.__GLOBAL__I_000101=function(){return e.asm.__GLOBAL__I_000101.apply(null,arguments)},bb=e.__GLOBAL__sub_I_XenepicRes_cpp=function(){return e.asm.__GLOBAL__sub_I_XenepicRes_cpp.apply(null,arguments)},cb=e.__GLOBAL__sub_I_iostream_cpp=function(){return e.asm.__GLOBAL__sub_I_iostream_cpp.apply(null,arguments)};e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};
var od=e._free=function(){return e.asm._free.apply(null,arguments)};e._main=function(){return e.asm._main.apply(null,arguments)};var wa=e._malloc=function(){return e.asm._malloc.apply(null,arguments)},Ca=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)};e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.dynCall_vidd=function(){return e.asm.dynCall_vidd.apply(null,arguments)};
e.dynCall_vii=function(){return e.asm.dynCall_vii.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.dynCall_viii.apply(null,arguments)};e.dynCall_viiii=function(){return e.asm.dynCall_viiii.apply(null,arguments)};e.dynCall_viiiii=function(){return e.asm.dynCall_viiiii.apply(null,arguments)};e.asm=Ge;e.getMemory=function(a){if(ia)if(Ta)var b=wa(a);else{assert(C);b=x[C>>2];a=b+a+15&-16;x[C>>2]=a;if(a=a>=D)La(),a=!0;a&&(x[C>>2]=b,b=0)}else b=ha(a);return b};e.addRunDependency=Ya;
e.removeRunDependency=Za;e.FS_createFolder=ec;e.FS_createPath=fc;e.FS_createDataFile=ic;e.FS_createPreloadedFile=mc;e.FS_createLazyFile=lc;e.FS_createLink=jc;e.FS_createDevice=O;e.FS_unlink=Vb;function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}fa.prototype=Error();fa.prototype.constructor=fa;Xa=function He(){e.calledRun||Ie();e.calledRun||(Xa=He)};
e.callMain=function(a){a=a||[];Ta||(Ta=!0,Na(Pa));var b=a.length+1,c=Ca(4*(b+1));x[c>>2]=Ba(e.thisProgram);for(var d=1;d<b;d++)x[(c>>2)+d]=Ba(a[d-1]);x[(c>>2)+b]=0;try{var f=e._main(b,c,0);Je(f,!0)}catch(g){g instanceof fa||("SimulateInfiniteLoop"==g?e.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),e.printErr("exception thrown: "+a),e.quit(1,g)))}finally{}};
function Ie(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!na)){Ta||(Ta=!0,Na(Pa));Na(Qa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&Ke&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Sa.unshift(b)}Na(Sa)}}a=a||e.arguments;if(!(0<Va)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ua();Na(Oa);0<Va||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);b()},1)):b())}}e.run=Ie;function Je(a,b){if(!b||!e.noExitRuntime||0!==a){if(!e.noExitRuntime&&(na=!0,Ia=void 0,Na(Ra),e.onExit))e.onExit(a);m&&process.exit(a);e.quit(a,new fa(a))}}e.exit=Je;function t(a){if(e.onAbort)e.onAbort(a);void 0!==a?(e.print(a),e.printErr(a),a=JSON.stringify(a)):a="";na=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=t;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Ke=!0;
e.noInitialRun&&(Ke=!1);e.noExitRuntime=!0;Ie();
